//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddOn_FE_DIAN.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddOn_FE_DIAN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select &quot;Code&quot;, &quot;Name&quot; 
        ///From &quot;@FEDIAN_CODDOC&quot;.
        /// </summary>
        internal static string ListaDocDIAN {
            get {
                return ResourceManager.GetString("ListaDocDIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select &quot;Code&quot;, &quot;U_Descripcion&quot; 
        ///From &quot;@FEDIAN_UM&quot;.
        /// </summary>
        internal static string ListaUM {
            get {
                return ResourceManager.GetString("ListaUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IF $[$38.1470002145.0] = &apos;Manual&apos;
        ///
        ///Begin
        ///
        ///SELECT T0.&quot;U_DIAN_UM&quot; FROM &quot;@FEDIAN_HOMOL_UM&quot; T0 WHERE T0.&quot;U_SAP_UM&quot; = $[$38.212.0]
        ///
        ///END
        ///
        ///IF $[$38.1470002145.0] != &apos;Manual&apos;
        ///
        ///Begin
        ///
        ///SELECT T0.&quot;U_dian_UM&quot; FROM &quot;@FEDIAN_HOMOL_UM&quot; T0 WHERE T0.&quot;U_SAP_UM&quot; = $[$38.1470002145.0]
        ///
        ///END.
        /// </summary>
        internal static string UM_DIAN {
            get {
                return ResourceManager.GetString("UM_DIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select C0.&quot;Unidad&quot;, C0.&quot;Descr&quot;
        ///From(
        ///	SELECT 
        ///	Case When IsNull(&quot;UomCode&quot;,&apos;&apos;) = &apos;Manual&apos; Then &quot;unitMsr&quot; Else &quot;UomCode&quot; End &quot;Unidad&quot;, 
        ///	&quot;unitMsr&quot; as &quot;Descr&quot; 
        ///	FROM INV1
        ///)C0 
        ///Where IsNull(&quot;Unidad&quot;,&apos;&apos;) != &apos;&apos; And C0.&quot;Unidad&quot; Not In (Select &quot;U_SAP_UM&quot; From &quot;@FEDIAN_HOMOL_UM&quot; Where IsNull(&quot;U_DIAN_UM&quot;,&apos;&apos;) != &apos;&apos;)
        ///Group By C0.&quot;Unidad&quot;, C0.Descr.
        /// </summary>
        internal static string UM_Pendientes {
            get {
                return ResourceManager.GetString("UM_Pendientes", resourceCulture);
            }
        }
    }
}
