//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddOn_FE_DIAN.consultarArchivosDispape {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wsconsultarpdfxml.webservice.dispapeles.com/", ConfigurationName="consultarArchivosDispape.ConsultarArchivos")]
    public interface ConsultarArchivos {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AddOn_FE_DIAN.consultarArchivosDispape.consultarArchivosResponse consultarArchivos(AddOn_FE_DIAN.consultarArchivosDispape.consultarArchivos1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<AddOn_FE_DIAN.consultarArchivosDispape.consultarArchivosResponse> consultarArchivosAsync(AddOn_FE_DIAN.consultarArchivosDispape.consultarArchivos1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsconsultarpdfxml.webservice.dispapeles.com/")]
    public partial class felConsultaFacturaArchivo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long consecutivoField;
        
        private bool consecutivoFieldSpecified;
        
        private string contraseniaField;
        
        private long idEmpresaField;
        
        private bool idEmpresaFieldSpecified;
        
        private string prefijoField;
        
        private int tipoArchivoField;
        
        private string tipoDocumentoField;
        
        private string tokenField;
        
        private string usuarioField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long consecutivo {
            get {
                return this.consecutivoField;
            }
            set {
                this.consecutivoField = value;
                this.RaisePropertyChanged("consecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool consecutivoSpecified {
            get {
                return this.consecutivoFieldSpecified;
            }
            set {
                this.consecutivoFieldSpecified = value;
                this.RaisePropertyChanged("consecutivoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                this.contraseniaField = value;
                this.RaisePropertyChanged("contrasenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                this.idEmpresaField = value;
                this.RaisePropertyChanged("idEmpresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEmpresaSpecified {
            get {
                return this.idEmpresaFieldSpecified;
            }
            set {
                this.idEmpresaFieldSpecified = value;
                this.RaisePropertyChanged("idEmpresaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string prefijo {
            get {
                return this.prefijoField;
            }
            set {
                this.prefijoField = value;
                this.RaisePropertyChanged("prefijo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int tipoArchivo {
            get {
                return this.tipoArchivoField;
            }
            set {
                this.tipoArchivoField = value;
                this.RaisePropertyChanged("tipoArchivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsconsultarpdfxml.webservice.dispapeles.com/")]
    public partial class felMensajesProceso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoMensajeField;
        
        private string descripcionMensajeField;
        
        private string rechazoNotificacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoMensaje {
            get {
                return this.codigoMensajeField;
            }
            set {
                this.codigoMensajeField = value;
                this.RaisePropertyChanged("codigoMensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcionMensaje {
            get {
                return this.descripcionMensajeField;
            }
            set {
                this.descripcionMensajeField = value;
                this.RaisePropertyChanged("descripcionMensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string rechazoNotificacion {
            get {
                return this.rechazoNotificacionField;
            }
            set {
                this.rechazoNotificacionField = value;
                this.RaisePropertyChanged("rechazoNotificacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsconsultarpdfxml.webservice.dispapeles.com/")]
    public partial class felArchivos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string formatoField;
        
        private string mimeTypeField;
        
        private string nameFileField;
        
        private byte[] streamFileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string formato {
            get {
                return this.formatoField;
            }
            set {
                this.formatoField = value;
                this.RaisePropertyChanged("formato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("mimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nameFile {
            get {
                return this.nameFileField;
            }
            set {
                this.nameFileField = value;
                this.RaisePropertyChanged("nameFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=3)]
        public byte[] streamFile {
            get {
                return this.streamFileField;
            }
            set {
                this.streamFileField = value;
                this.RaisePropertyChanged("streamFile");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsconsultarpdfxml.webservice.dispapeles.com/")]
    public partial class felRepuestaDescargaDocumentos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoRespuestaField;
        
        private long consecutivoField;
        
        private bool consecutivoFieldSpecified;
        
        private string descripcionRespuestaField;
        
        private int estadoProcesoField;
        
        private string idErpField;
        
        private felArchivos[] listaArchivosField;
        
        private felMensajesProceso[] listaMensajesProcesoField;
        
        private string prefijoField;
        
        private string tipoDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("codigoRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long consecutivo {
            get {
                return this.consecutivoField;
            }
            set {
                this.consecutivoField = value;
                this.RaisePropertyChanged("consecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool consecutivoSpecified {
            get {
                return this.consecutivoFieldSpecified;
            }
            set {
                this.consecutivoFieldSpecified = value;
                this.RaisePropertyChanged("consecutivoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcionRespuesta {
            get {
                return this.descripcionRespuestaField;
            }
            set {
                this.descripcionRespuestaField = value;
                this.RaisePropertyChanged("descripcionRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int estadoProceso {
            get {
                return this.estadoProcesoField;
            }
            set {
                this.estadoProcesoField = value;
                this.RaisePropertyChanged("estadoProceso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string idErp {
            get {
                return this.idErpField;
            }
            set {
                this.idErpField = value;
                this.RaisePropertyChanged("idErp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaArchivos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public felArchivos[] listaArchivos {
            get {
                return this.listaArchivosField;
            }
            set {
                this.listaArchivosField = value;
                this.RaisePropertyChanged("listaArchivos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaMensajesProceso", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public felMensajesProceso[] listaMensajesProceso {
            get {
                return this.listaMensajesProcesoField;
            }
            set {
                this.listaMensajesProcesoField = value;
                this.RaisePropertyChanged("listaMensajesProceso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string prefijo {
            get {
                return this.prefijoField;
            }
            set {
                this.prefijoField = value;
                this.RaisePropertyChanged("prefijo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarArchivos", WrapperNamespace="http://wsconsultarpdfxml.webservice.dispapeles.com/", IsWrapped=true)]
    public partial class consultarArchivos1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsconsultarpdfxml.webservice.dispapeles.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AddOn_FE_DIAN.consultarArchivosDispape.felConsultaFacturaArchivo Fel_ConsultaFacturaArchivo;
        
        public consultarArchivos1() {
        }
        
        public consultarArchivos1(AddOn_FE_DIAN.consultarArchivosDispape.felConsultaFacturaArchivo Fel_ConsultaFacturaArchivo) {
            this.Fel_ConsultaFacturaArchivo = Fel_ConsultaFacturaArchivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarArchivosResponse", WrapperNamespace="http://wsconsultarpdfxml.webservice.dispapeles.com/", IsWrapped=true)]
    public partial class consultarArchivosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsconsultarpdfxml.webservice.dispapeles.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AddOn_FE_DIAN.consultarArchivosDispape.felRepuestaDescargaDocumentos @return;
        
        public consultarArchivosResponse() {
        }
        
        public consultarArchivosResponse(AddOn_FE_DIAN.consultarArchivosDispape.felRepuestaDescargaDocumentos @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultarArchivosChannel : AddOn_FE_DIAN.consultarArchivosDispape.ConsultarArchivos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarArchivosClient : System.ServiceModel.ClientBase<AddOn_FE_DIAN.consultarArchivosDispape.ConsultarArchivos>, AddOn_FE_DIAN.consultarArchivosDispape.ConsultarArchivos {
        
        public ConsultarArchivosClient() {
        }
        
        public ConsultarArchivosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultarArchivosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarArchivosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarArchivosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AddOn_FE_DIAN.consultarArchivosDispape.consultarArchivosResponse AddOn_FE_DIAN.consultarArchivosDispape.ConsultarArchivos.consultarArchivos(AddOn_FE_DIAN.consultarArchivosDispape.consultarArchivos1 request) {
            return base.Channel.consultarArchivos(request);
        }
        
        public AddOn_FE_DIAN.consultarArchivosDispape.felRepuestaDescargaDocumentos consultarArchivos(AddOn_FE_DIAN.consultarArchivosDispape.felConsultaFacturaArchivo Fel_ConsultaFacturaArchivo) {
            AddOn_FE_DIAN.consultarArchivosDispape.consultarArchivos1 inValue = new AddOn_FE_DIAN.consultarArchivosDispape.consultarArchivos1();
            inValue.Fel_ConsultaFacturaArchivo = Fel_ConsultaFacturaArchivo;
            AddOn_FE_DIAN.consultarArchivosDispape.consultarArchivosResponse retVal = ((AddOn_FE_DIAN.consultarArchivosDispape.ConsultarArchivos)(this)).consultarArchivos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AddOn_FE_DIAN.consultarArchivosDispape.consultarArchivosResponse> AddOn_FE_DIAN.consultarArchivosDispape.ConsultarArchivos.consultarArchivosAsync(AddOn_FE_DIAN.consultarArchivosDispape.consultarArchivos1 request) {
            return base.Channel.consultarArchivosAsync(request);
        }
        
        public System.Threading.Tasks.Task<AddOn_FE_DIAN.consultarArchivosDispape.consultarArchivosResponse> consultarArchivosAsync(AddOn_FE_DIAN.consultarArchivosDispape.felConsultaFacturaArchivo Fel_ConsultaFacturaArchivo) {
            AddOn_FE_DIAN.consultarArchivosDispape.consultarArchivos1 inValue = new AddOn_FE_DIAN.consultarArchivosDispape.consultarArchivos1();
            inValue.Fel_ConsultaFacturaArchivo = Fel_ConsultaFacturaArchivo;
            return ((AddOn_FE_DIAN.consultarArchivosDispape.ConsultarArchivos)(this)).consultarArchivosAsync(inValue);
        }
    }
}
