//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddOn_FE_DIAN {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Querys : global::System.Configuration.ApplicationSettingsBase {
        
        private static Querys defaultInstance = ((Querys)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Querys())));
        
        public static Querys Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select \'6\' as \"version\", \'2\' as \"tipodocumento\", \'1\' as \"codigoPlantillaPdf\", IfN" +
            "ull(A3.\"BeginStr\",\'\') as \"prefijo\", \r\nA0.\"U_SEI_FEConcepNC\" as \"tiponota\", A0.\"D" +
            "ocNum\" as \"consecutivo\", A0.\"U_SEI_FETipOper\" as \"tipoOperacion\",\r\nTO_NVARCHAR(A" +
            "0.\"DocDate\", \'YYYY-MM-DD\') as \"fechafacturacion\", TO_NVARCHAR(A0.\"DocDueDate\", \'" +
            "YYYY-MM-DD\') as \"fechavencimiento\",\r\nCase When A0.\"DocCur\" = \'$\' Then \'COP\' Else" +
            " \'COP\' End \"moneda\", A6.\"SubTotal\" as \"totalimportebruto\", \r\nA7.\"baseimpu\" as \"t" +
            "otalbaseimponible\", (A6.\"SubTotal\" + A0.\"VatSum\") as \"totalbaseconimpuestos\",\r\nA" +
            "0.\"DiscSum\" as \"totalDescuento\", A0.\"DiscPrcnt\" as \"campoAdicional3\",\r\n\'TEXTO EN" +
            "CABEZADO\' as \"campoAdicional6\", \'COP\' as \"codigoMonedaCambio\",\r\nA2.\"U_SEI_FERegF" +
            "is\" \"regimen\",\r\nA0.\"DocTotal\" + IfNull(A14.\"TotalRet\",0) as \"totalfactura\", A0.\"" +
            "DpmAppl\" as \"pagoanticipado\",  A0.\"Comments\" as \"descripcion\",\r\nCase When A2.\"U_" +
            "HBT_TipEnt\" = \'1\' Then \'2\' When A2.\"U_HBT_TipEnt\" = \'2\' Then \'1\' Else \'1\' End \"t" +
            "ipopersona\",\r\nCase When A2.\"U_HBT_TipEnt\" = \'2\' Then IfNull(A2.\"CardName\",\'\') \r\n" +
            "Else IfNull(A2.\"U_HBT_Nombres\",\'\') || \' \' || IfNull(A2.\"U_HBT_Apellido1\",\'\') || " +
            "\' \' || IfNull(A2.\"U_HBT_Apellido2\",\'\') End \"nombreCompleto\",\r\nIfNull(A2.\"U_HBT_T" +
            "ipDoc\",\'\') as \"tipoidentificacion\",\r\nCase When IfNull(Locate(A2.\"LicTradNum\",\'-\'" +
            "),0) = 0 Then A2.\"LicTradNum\" Else SubString(A2.\"LicTradNum\", 1, Locate(A2.\"LicT" +
            "radNum\", \'-\')-1) End \"numeroidentificacion\",\r\nCase When Locate(A1.\"LicTradNum\",\'" +
            "-\') = 0 Then \'\' Else SubString(A0.\"LicTradNum\", (Locate(A0.\"LicTradNum\", \'-\')+1)" +
            ",1) End \"digitoverificacion\",\r\n\'SI\' as \"aplicafel\", \'EMAIL\' as \"envioPorEmailPla" +
            "taforma\", A2.\"E_Mail\" as \"email\", \r\nA2.\"Country\" as \"pais\", A13.\"Name\" as \"paisn" +
            "ombre\",\r\nSUBSTRING(A2.\"U_HBT_MunMed\",1,2) as \"departamento\", A4.\"U_NomDepartamen" +
            "to\" as \"nombredepartamento\",\r\nA2.\"U_HBT_MunMed\" as \"codigoCiudad\", A4.\"Name\" as " +
            "\"descripcionCiudad\",\r\nA2.\"Address\" as \"direccion\", A2.\"Phone1\" as \"telefono\", Ca" +
            "se When A0.\"GroupNum\" = \'-1\' Then \'1\' Else \'2\' End \"tipocompra\",\r\nA2.\"BillToDef\"" +
            " as \"despachadoANombre\", A2.\"Phone1\" as \"telefonoEntrega\", A2.\"Address\" as \"dire" +
            "ccionEntrega\", A2.\"Country\" as \"paisEntrega\",\r\nCase When A0.\"DocType\" = \'S\' Then" +
            " A1.\"AcctCode\" Else A1.\"ItemCode\" End as \"codigoproducto\", \r\nA10.\"U_SEI_FEIdent\"" +
            " as \"tipocodigoproducto\",\r\nA1.\"Dscription\" as \"referencia\", A1.\"Dscription\" as \"" +
            "descripcionLine\", A1.\"Dscription\" as \"nombreProducto\", \r\nCase When A0.\"DocType\" " +
            "= \'S\' Then 1 Else Cast(A1.\"Quantity\" as decimal(28,8)) End as \"cantidad\",\r\nCASE " +
            "\r\nWHEN IfNull(A1.\"UomCode\",\'\') = \'Manual\' Then (Select IfNull(P0.\"U_DIAN_UM\",\'\')" +
            " From \"@FEDIAN_HOMOL_UM\" P0 Where P0.\"U_SAP_UM\" = A1.\"unitMsr\") \r\nElse (Select I" +
            "fNull(P0.\"U_DIAN_UM\",\'\') From \"@FEDIAN_HOMOL_UM\" P0 Where P0.\"U_SAP_UM\" = A1.\"Uo" +
            "mCode\") End \"unidadmedida\", \r\nA1.\"PriceBefDi\" as \"valorunitario\", \r\nA1.\"LineTota" +
            "l\" as \"preciosinimpuestos\", \r\nA1.\"LineTotal\" as \"preciototal\", Cast(A1.\"DiscPrcn" +
            "t\" as decimal(28,8)) as \"porcentajedescuento\",\r\nA0.\"U_SEI_FEMedPago\" as \"medioPa" +
            "go\", A5.\"PymntGroup\" as \"nombreCondPago\", A0.\"U_CuidadEmi\" as \"documentoEmitidoE" +
            "n\",\r\nCase When A0.\"GroupNum\" = \'-1\' Then \'1\' Else A5.\"ExtraMonth\"*30 + A5.\"Extra" +
            "Days\" End \"periododepagoa\",\r\nCase\r\nWhen A1.\"TaxCode\" = \'IVAEXENT\' Then \'3\'\r\nWhen" +
            " A1.\"TaxCode\" = \'IVAGEV0\' Then \'2\'\r\nWhen A1.\"TaxCode\" = \'IVANOGRV\' Then \'2\'\r\nEls" +
            "e \'1\' End \"tipoImpuesto\", \r\nA12.\"U_SEI_FETributo\" as \"codigoImpuestoRetencion\", " +
            "Cast(A11.\"TaxRate\" as decimal(28,8)) as \"porcentaje\",\r\nA11.\"TaxSum\" as \"valorImp" +
            "uestoRetencion\", Case When IfNull(A11.\"TaxSum\",0) = 0 Then 0 Else A11.\"BaseSum\" " +
            "End as \"baseimponible\",\r\n\'false\' as \"isAutoRetenido\", IfNull(A9.\"string\",\'ZZ\') a" +
            "s \"tipoobligacion\",\r\nIfNull(A0.\"U_SEI_FEDescu\",\'\') as \"codigoDescuentoCab\", A0.\"" +
            "DiscSum\" as \"descuentoCab\", A0.\"DiscPrcnt\" as \"porcentajeDescuentoCab\",\r\nIfNull(" +
            "A1.\"U_SEI_FEDescu\",\'\') as \"codigoDescuentoLin\", A1.\"PriceBefDi\"*(A1.\"DiscPrcnt\"/" +
            "100) as \"descuentoLin\", A1.\"DiscPrcnt\" as \"porcentajeDescuentoLin\",\r\nA15.\"U_Foli" +
            "o\" as \"consecutivofacturamodificada\", A15.\"U_Prefijo\" as \"prefijoFacturaModifica" +
            "da\", A15.\"U_ProcessID\" as \"cufefacturamodificada\", \r\nA15.\"U_Fecha_Envio\" as \"fec" +
            "hafacturamodificada\",\'1\' as \"tipoDocumentoFacturaModificada\"\r\nFrom \"ORIN\" A0\r\nIn" +
            "ner Join \"RIN1\" A1 On A0.\"DocEntry\" = A1.\"DocEntry\"\r\nInner Join \"OCRD\" A2 On A0." +
            "\"CardCode\" = A2.\"CardCode\"\r\nInner Join \"NNM1\" A3 On A0.\"Series\" = A3.\"Series\"\r\nL" +
            "eft Join \"@HBT_MUNICIPIO\" A4 On A2.\"U_HBT_MunMed\" = A4.\"Code\"\r\nInner Join \"OCTG\"" +
            " A5 On A0.\"GroupNum\" = A5.\"GroupNum\"\r\nLeft Join (Select \"DocEntry\", Sum(\"LineTot" +
            "al\") as \"SubTotal\" From \"RIN1\" Group By \"DocEntry\") A6 On A0.\"DocEntry\" = A6.\"Do" +
            "cEntry\"\r\nLeft Join (Select \"DocEntry\", Sum(\"BaseSum\") as \"baseimpu\" From \"RIN4\" " +
            "Where IfNull(\"TaxSum\",0) != 0 Group By \"DocEntry\") A7 On A0.\"DocEntry\" = A7.\"Doc" +
            "Entry\"\r\nLeft Join \"OADM\" A8 On 1 = 1\r\nLeft Join (Select \"Code\", STRING_AGG(\"U_Co" +
            "digo\",\';\') As \"string\" From \"@FEDIAN_SNRES\"\r\n\t\t\t\tGroup By \"Code\") A9 On A2.\"Card" +
            "Code\" = A9.\"Code\"\r\nLeft Join \"OITM\" A10 On A1.\"ItemCode\" = A10.\"ItemCode\"\r\nLeft " +
            "Join \"RIN4\" A11 On A1.\"DocEntry\" = A11.\"DocEntry\" And A1.\"LineNum\" = A11.\"LineNu" +
            "m\" And A11.\"RelateType\" = \'1\'\r\nLeft Join \"OSTC\" A12 On A11.\"StcCode\" = A12.\"Code" +
            "\"\r\nLeft Join \"OCRY\" A13 On A2.\"Country\" = A13.\"Code\"\r\nLeft Join (\r\n\t\t\tSelect B0." +
            "\"AbsEntry\" , Sum(B0.\"WTAmnt\") as \"TotalRet\"\r\n\t\t\tFrom \"RIN5\" B0 \r\n\t\t\tInner Join \"" +
            "OWHT\" B1 On B0.\"WTCode\" = B1.\"WTCode\" And B1.\"U_HBT_TipRet\" != 0\r\n\t\t\tGroup By B1" +
            ".\"U_HBT_TipRet\", B0.\"AbsEntry\"\r\n\t\t  ) A14 On A0.\"DocEntry\" = A14.\"AbsEntry\"\r\nLef" +
            "t Join \"@FEDIAN_MONITORLOG\" A15 On A1.\"BaseType\" = A15.\"U_ObjType\" And A1.\"BaseE" +
            "ntry\" = A15.\"U_DocNum\"\r\nWhere A0.\"DocEntry\" = {0} And A1.\"TreeType\" != \'I\';")]
        public string NotaCredito {
            get {
                return ((string)(this["NotaCredito"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select \'6\' as \"version\", \'1\' as \"tipodocumento\", \'1\' as \"codigoPlantillaPdf\", IfN" +
            "ull(A3.\"BeginStr\",\'\') as \"prefijo\", \r\nA0.\"U_TipoNota\" as \"tiponota\", A0.\"DocNum\"" +
            " as \"consecutivo\", A0.\"U_SEI_FETipOper\" as \"tipoOperacion\",\r\nTO_NVARCHAR(A0.\"Doc" +
            "Date\", \'YYYY-MM-DD\') as \"fechafacturacion\", TO_NVARCHAR(A0.\"DocDueDate\", \'YYYY-M" +
            "M-DD\') as \"fechavencimiento\",\r\nCase When A0.\"DocCur\" = \'$\' Then \'COP\' Else \'COP\'" +
            " End \"moneda\", A6.\"SubTotal\" as \"totalimportebruto\", \r\nA7.\"baseimpu\" as \"totalba" +
            "seimponible\", (A6.\"SubTotal\" + A0.\"VatSum\") as \"totalbaseconimpuestos\",\r\nA0.\"Dis" +
            "cSum\" as \"totalDescuento\", A0.\"DiscPrcnt\" as \"campoAdicional3\",\r\n\'TEXTO ENCABEZA" +
            "DO\' as \"campoAdicional6\", \'COP\' as \"codigoMonedaCambio\",\r\nA2.\"U_SEI_FERegFis\" \"r" +
            "egimen\",\r\nA0.\"DocTotal\" + IfNull(A14.\"TotalRet\",0) as \"totalfactura\", A0.\"DpmApp" +
            "l\" as \"pagoanticipado\",  A0.\"Comments\" as \"descripcion\",\r\nCase When A2.\"U_HBT_Ti" +
            "pEnt\" = \'1\' Then \'2\' When A2.\"U_HBT_TipEnt\" = \'2\' Then \'1\' Else \'1\' End \"tipoper" +
            "sona\",\r\nCase When A2.\"U_HBT_TipEnt\" = \'2\' Then IfNull(A2.\"CardName\",\'\') \r\nElse I" +
            "fNull(A2.\"U_HBT_Nombres\",\'\') || \' \' || IfNull(A2.\"U_HBT_Apellido1\",\'\') || \' \' ||" +
            " IfNull(A2.\"U_HBT_Apellido2\",\'\') End \"nombreCompleto\",\r\nIfNull(A2.\"U_HBT_TipDoc\"" +
            ",\'\') as \"tipoidentificacion\",\r\nCase When IfNull(Locate(A2.\"LicTradNum\",\'-\'),0) =" +
            " 0 Then A2.\"LicTradNum\" Else SubString(A2.\"LicTradNum\", 1, Locate(A2.\"LicTradNum" +
            "\", \'-\')-1) End \"numeroidentificacion\",\r\nCase When Locate(A1.\"LicTradNum\",\'-\') = " +
            "0 Then \'\' Else SubString(A0.\"LicTradNum\", (Locate(A0.\"LicTradNum\", \'-\')+1),1) En" +
            "d \"digitoverificacion\",\r\n\'SI\' as \"aplicafel\", \'EMAIL\' as \"envioPorEmailPlataform" +
            "a\", A2.\"E_Mail\" as \"email\", \r\nA2.\"Country\" as \"pais\", A13.\"Name\" as \"paisnombre\"" +
            ",\r\nSUBSTRING(A2.\"U_HBT_MunMed\",1,2) as \"departamento\", A4.\"U_NomDepartamento\" as" +
            " \"nombredepartamento\",\r\nA2.\"U_HBT_MunMed\" as \"codigoCiudad\", A4.\"Name\" as \"descr" +
            "ipcionCiudad\",\r\nA2.\"Address\" as \"direccion\", A2.\"Phone1\" as \"telefono\", Case Whe" +
            "n A0.\"GroupNum\" = \'-1\' Then \'1\' Else \'2\' End \"tipocompra\",\r\nA2.\"BillToDef\" as \"d" +
            "espachadoANombre\", A2.\"Phone1\" as \"telefonoEntrega\", A2.\"Address\" as \"direccionE" +
            "ntrega\", A2.\"Country\" as \"paisEntrega\",\r\nCase When A0.\"DocType\" = \'S\' Then A1.\"A" +
            "cctCode\" Else A1.\"ItemCode\" End as \"codigoproducto\", \r\nA10.\"U_SEI_FEIdent\" as \"t" +
            "ipocodigoproducto\",\r\nA1.\"Dscription\" as \"referencia\", A1.\"Dscription\" as \"descri" +
            "pcionLine\", A1.\"Dscription\" as \"nombreProducto\", \r\nCase When A0.\"DocType\" = \'S\' " +
            "Then 1 Else Cast(A1.\"Quantity\" as decimal(28,8)) End as \"cantidad\",\r\nCASE \r\nWHEN" +
            " IfNull(A1.\"UomCode\",\'\') = \'Manual\' Then (Select IfNull(P0.\"U_DIAN_UM\",\'\') From " +
            "\"@FEDIAN_HOMOL_UM\" P0 Where P0.\"U_SAP_UM\" = A1.\"unitMsr\") \r\nElse (Select IfNull(" +
            "P0.\"U_DIAN_UM\",\'\') From \"@FEDIAN_HOMOL_UM\" P0 Where P0.\"U_SAP_UM\" = A1.\"UomCode\"" +
            ") End \"unidadmedida\", \r\nA1.\"PriceBefDi\" as \"valorunitario\", \r\nA1.\"LineTotal\" as " +
            "\"preciosinimpuestos\", \r\nA1.\"LineTotal\" as \"preciototal\", Cast(A1.\"DiscPrcnt\" as " +
            "decimal(28,8)) as \"porcentajedescuento\",\r\nA0.\"U_SEI_FEMedPago\" as \"medioPago\", A" +
            "5.\"PymntGroup\" as \"nombreCondPago\", A0.\"U_CuidadEmi\" as \"documentoEmitidoEn\",\r\nC" +
            "ase When A0.\"GroupNum\" = \'-1\' Then \'1\' Else A5.\"ExtraMonth\"*30 + A5.\"ExtraDays\" " +
            "End \"periododepagoa\",\r\nCase\r\nWhen A1.\"TaxCode\" = \'IVAEXENT\' Then \'3\'\r\nWhen A1.\"T" +
            "axCode\" = \'IVAGEV0\' Then \'2\'\r\nWhen A1.\"TaxCode\" = \'IVANOGRV\' Then \'2\'\r\nElse \'1\' " +
            "End \"tipoImpuesto\", \r\nA12.\"U_SEI_FETributo\" as \"codigoImpuestoRetencion\", Cast(A" +
            "11.\"TaxRate\" as decimal(28,8)) as \"porcentaje\",\r\nA11.\"TaxSum\" as \"valorImpuestoR" +
            "etencion\", Case When IfNull(A11.\"TaxSum\",0) = 0 Then 0 Else A11.\"BaseSum\" End as" +
            " \"baseimponible\",\r\n\'false\' as \"isAutoRetenido\", IfNull(A9.\"string\",\'ZZ\') as \"tip" +
            "oobligacion\",\r\nIfNull(A0.\"U_SEI_FEDescu\",\'\') as \"codigoDescuentoCab\", A0.\"DiscSu" +
            "m\" as \"descuentoCab\", A0.\"DiscPrcnt\" as \"porcentajeDescuentoCab\",\r\nIfNull(A1.\"U_" +
            "SEI_FEDescu\",\'\') as \"codigoDescuentoLin\", A1.\"PriceBefDi\"*(A1.\"DiscPrcnt\"/100) a" +
            "s \"descuentoLin\", A1.\"DiscPrcnt\" as \"porcentajeDescuentoLin\"\r\nFrom \"OINV\" A0\r\nIn" +
            "ner Join \"INV1\" A1 On A0.\"DocEntry\" = A1.\"DocEntry\"\r\nInner Join \"OCRD\" A2 On A0." +
            "\"CardCode\" = A2.\"CardCode\"\r\nInner Join \"NNM1\" A3 On A0.\"Series\" = A3.\"Series\"\r\nL" +
            "eft Join \"@HBT_MUNICIPIO\" A4 On A2.\"U_HBT_MunMed\" = A4.\"Code\"\r\nInner Join \"OCTG\"" +
            " A5 On A0.\"GroupNum\" = A5.\"GroupNum\"\r\nLeft Join (Select \"DocEntry\", Sum(\"LineTot" +
            "al\") as \"SubTotal\" From \"INV1\" Group By \"DocEntry\") A6 On A0.\"DocEntry\" = A6.\"Do" +
            "cEntry\"\r\nLeft Join (Select \"DocEntry\", Sum(\"BaseSum\") as \"baseimpu\" From \"INV4\" " +
            "Where IfNull(\"TaxSum\",0) != 0 Group By \"DocEntry\") A7 On A0.\"DocEntry\" = A7.\"Doc" +
            "Entry\"\r\nLeft Join \"OADM\" A8 On 1 = 1\r\nLeft Join (Select \"Code\", STRING_AGG(\"U_Co" +
            "digo\",\';\') As \"string\" From \"@FEDIAN_SNRES\"\r\n\t\t\t\tGroup By \"Code\") A9 On A2.\"Card" +
            "Code\" = A9.\"Code\"\r\nLeft Join \"OITM\" A10 On A1.\"ItemCode\" = A10.\"ItemCode\"\r\nLeft " +
            "Join \"INV4\" A11 On A1.\"DocEntry\" = A11.\"DocEntry\" And A1.\"LineNum\" = A11.\"LineNu" +
            "m\" And A11.\"RelateType\" = \'1\'\r\nLeft Join \"OSTC\" A12 On A11.\"StcCode\" = A12.\"Code" +
            "\"\r\nLeft Join \"OCRY\" A13 On A2.\"Country\" = A13.\"Code\"\r\nLeft Join (\r\n\t\t\tSelect B0." +
            "\"AbsEntry\" , Sum(B0.\"WTAmnt\") as \"TotalRet\"\r\n\t\t\tFrom \"INV5\" B0 \r\n\t\t\tInner Join \"" +
            "OWHT\" B1 On B0.\"WTCode\" = B1.\"WTCode\" And B1.\"U_HBT_TipRet\" != 0\r\n\t\t\tGroup By B1" +
            ".\"U_HBT_TipRet\", B0.\"AbsEntry\"\r\n\t\t  ) A14 On A0.\"DocEntry\" = A14.\"AbsEntry\"\r\nWhe" +
            "re A0.\"DocEntry\" = {0} And A1.\"TreeType\" != \'I\';")]
        public string FacturaVenta {
            get {
                return ((string)(this["FacturaVenta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Select 
A0.""Code"", A0.""U_ObjType"" as ""Tipo Objeto"", A0.""U_DocType"" as ""Tipo Documento"", A1.""Name"" as ""Documento DIAN"", A0.""U_Folio"" as ""Numero Documento"", A0.""U_Prefijo"" as ""Prefijo"", A0.""U_DocNum"" as ""Numero Interno"", 
A0.""U_Status"" as ""Codigo Estado"", A0.""U_Resultado"" as ""Descripcion Estado"", A0.""U_ProcessID"" as ""ID Proceso"", 
A0.""U_Fecha_Envio"" as ""Fecha de contabilizacion"", A0.""U_Hora_Envio"" as ""Hora de creacion"", A0.""U_Usuario_Envio"" as ""Usuario Envio"", 
A0.""U_Det_Peticion"" as ""Detalle Peticion"", A0.""U_Respuesta_Int"" as ""Respuesta Integracion"", A0.""U_Archivo_PDF"" as ""Archivo PDF"", A0.""U_Enlace_XML"" as ""Archivo XML"",
A0.""U_ID_Seguimiento"" as ""FebosID""
From ""@FEDIAN_MONITORLOG"" A0
Left Join ""@FEDIAN_CODDOC"" A1 On A0.""U_DocType"" = A1.""Code""
Where A0.""U_Fecha_Envio"" Between '{0}' and '{1}' and (A0.""U_DocType"" = '{2}' OR IfNull('{2}','')='') and (A0.""U_Status"" = '{3}' OR IfNull('{3}','')='')
Order By Cast(A0.""Code"" as int)")]
        public string CargueMonitor {
            get {
                return ((string)(this["CargueMonitor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select * from \"@FEDIAN_PARAMG\"")]
        public string PARAMG {
            get {
                return ((string)(this["PARAMG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select \"Code\" From \"@FEDIAN_MONITORLOG\" Where \"U_DocNum\" = {0}")]
        public string GetCodeLog {
            get {
                return ((string)(this["GetCodeLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Select ""Code"", ""U_ProcessID"" as ""ProcessID"", ""U_ID_Seguimiento"" as ""ID_Seguimiento"", ""U_Det_Peticion"" as ""Det_Peticion""
From ""@FEDIAN_MONITORLOG""
Where (IfNull(""U_Status"",'') in ({0})) Or (IfNull(""U_Status"",'') = '' And IfNull(Cast(""U_Archivo_PDF"" as Nvarchar(2500)), '') = '' )")]
        public string ProcessStatus {
            get {
                return ((string)(this["ProcessStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FacturaExpo {
            get {
                return ((string)(this["FacturaExpo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select \'6\' as \"version\", \'5\' as \"tipodocumento\", \'1\' as \"codigoPlantillaPdf\", IfN" +
            "ull(A3.\"BeginStr\",\'\') as \"prefijo\", \r\nA0.\"U_TipoNota\" as \"tiponota\", A0.\"DocNum\"" +
            " as \"consecutivo\", A0.\"U_SEI_FETipOper\" as \"tipoOperacion\",\r\nTO_NVARCHAR(A0.\"Doc" +
            "Date\", \'YYYY-MM-DD\') as \"fechafacturacion\", TO_NVARCHAR(A0.\"DocDueDate\", \'YYYY-M" +
            "M-DD\') as \"fechavencimiento\",\r\nCase When A0.\"DocCur\" = \'$\' Then \'COP\' Else \'COP\'" +
            " End \"moneda\", A6.\"SubTotal\" as \"totalimportebruto\", \r\nA7.\"baseimpu\" as \"totalba" +
            "seimponible\", (A6.\"SubTotal\" + A0.\"VatSum\") as \"totalbaseconimpuestos\",\r\nA0.\"Dis" +
            "cSum\" as \"totalDescuento\", A0.\"DiscPrcnt\" as \"campoAdicional3\",\r\n\'TEXTO ENCABEZA" +
            "DO\' as \"campoAdicional6\", \'COP\' as \"codigoMonedaCambio\",\r\nA2.\"U_SEI_FERegFis\" \"r" +
            "egimen\",\r\nA0.\"DocTotal\" + IfNull(A14.\"TotalRet\",0) as \"totalfactura\", A0.\"DpmApp" +
            "l\" as \"pagoanticipado\",  A0.\"Comments\" as \"descripcion\",\r\nCase When A2.\"U_HBT_Ti" +
            "pEnt\" = \'1\' Then \'2\' When A2.\"U_HBT_TipEnt\" = \'2\' Then \'1\' Else \'1\' End \"tipoper" +
            "sona\",\r\nCase When A2.\"U_HBT_TipEnt\" = \'2\' Then IfNull(A2.\"CardName\",\'\') \r\nElse I" +
            "fNull(A2.\"U_HBT_Nombres\",\'\') || \' \' || IfNull(A2.\"U_HBT_Apellido1\",\'\') || \' \' ||" +
            " IfNull(A2.\"U_HBT_Apellido2\",\'\') End \"nombreCompleto\",\r\nIfNull(A2.\"U_HBT_TipDoc\"" +
            ",\'\') as \"tipoidentificacion\",\r\nCase When IfNull(Locate(A2.\"LicTradNum\",\'-\'),0) =" +
            " 0 Then A2.\"LicTradNum\" Else SubString(A2.\"LicTradNum\", 1, Locate(A2.\"LicTradNum" +
            "\", \'-\')-1) End \"numeroidentificacion\",\r\nCase When Locate(A1.\"LicTradNum\",\'-\') = " +
            "0 Then \'\' Else SubString(A0.\"LicTradNum\", (Locate(A0.\"LicTradNum\", \'-\')+1),1) En" +
            "d \"digitoverificacion\",\r\n\'SI\' as \"aplicafel\", \'EMAIL\' as \"envioPorEmailPlataform" +
            "a\", A2.\"E_Mail\" as \"email\", \r\nA2.\"Country\" as \"pais\", A13.\"Name\" as \"paisnombre\"" +
            ",\r\nSUBSTRING(A2.\"U_HBT_MunMed\",1,2) as \"departamento\", A4.\"U_NomDepartamento\" as" +
            " \"nombredepartamento\",\r\nA2.\"U_HBT_MunMed\" as \"codigoCiudad\", A4.\"Name\" as \"descr" +
            "ipcionCiudad\",\r\nA2.\"Address\" as \"direccion\", A2.\"Phone1\" as \"telefono\", Case Whe" +
            "n A0.\"GroupNum\" = \'-1\' Then \'1\' Else \'2\' End \"tipocompra\",\r\nA2.\"BillToDef\" as \"d" +
            "espachadoANombre\", A2.\"Phone1\" as \"telefonoEntrega\", A2.\"Address\" as \"direccionE" +
            "ntrega\", A2.\"Country\" as \"paisEntrega\",\r\nCase When A0.\"DocType\" = \'S\' Then A1.\"A" +
            "cctCode\" Else A1.\"ItemCode\" End as \"codigoproducto\", \r\nA10.\"U_SEI_FEIdent\" as \"t" +
            "ipocodigoproducto\",\r\nA1.\"Dscription\" as \"referencia\", A1.\"Dscription\" as \"descri" +
            "pcionLine\", A1.\"Dscription\" as \"nombreProducto\", \r\nCase When A0.\"DocType\" = \'S\' " +
            "Then 1 Else Cast(A1.\"Quantity\" as decimal(28,8)) End as \"cantidad\",\r\nCASE \r\nWHEN" +
            " IfNull(A1.\"UomCode\",\'\') = \'Manual\' Then (Select IfNull(P0.\"U_DIAN_UM\",\'\') From " +
            "\"@FEDIAN_HOMOL_UM\" P0 Where P0.\"U_SAP_UM\" = A1.\"unitMsr\") \r\nElse (Select IfNull(" +
            "P0.\"U_DIAN_UM\",\'\') From \"@FEDIAN_HOMOL_UM\" P0 Where P0.\"U_SAP_UM\" = A1.\"UomCode\"" +
            ") End \"unidadmedida\", \r\nA1.\"PriceBefDi\" as \"valorunitario\", \r\nA1.\"LineTotal\" as " +
            "\"preciosinimpuestos\", \r\nA1.\"LineTotal\" as \"preciototal\", Cast(A1.\"DiscPrcnt\" as " +
            "decimal(28,8)) as \"porcentajedescuento\",\r\nA0.\"U_SEI_FEMedPago\" as \"medioPago\", A" +
            "5.\"PymntGroup\" as \"nombreCondPago\", A0.\"U_CuidadEmi\" as \"documentoEmitidoEn\",\r\nC" +
            "ase When A0.\"GroupNum\" = \'-1\' Then \'1\' Else A5.\"ExtraMonth\"*30 + A5.\"ExtraDays\" " +
            "End \"periododepagoa\",\r\nCase\r\nWhen A1.\"TaxCode\" = \'IVAEXENT\' Then \'3\'\r\nWhen A1.\"T" +
            "axCode\" = \'IVAGEV0\' Then \'2\'\r\nWhen A1.\"TaxCode\" = \'IVANOGRV\' Then \'2\'\r\nElse \'1\' " +
            "End \"tipoImpuesto\", \r\nA12.\"U_SEI_FETributo\" as \"codigoImpuestoRetencion\", Cast(A" +
            "11.\"TaxRate\" as decimal(28,8)) as \"porcentaje\",\r\nA11.\"TaxSum\" as \"valorImpuestoR" +
            "etencion\", Case When IfNull(A11.\"TaxSum\",0) = 0 Then 0 Else A11.\"BaseSum\" End as" +
            " \"baseimponible\",\r\n\'false\' as \"isAutoRetenido\", IfNull(A9.\"string\",\'ZZ\') as \"tip" +
            "oobligacion\",\r\nIfNull(A0.\"U_SEI_FEDescu\",\'\') as \"codigoDescuentoCab\", A0.\"DiscSu" +
            "m\" as \"descuentoCab\", A0.\"DiscPrcnt\" as \"porcentajeDescuentoCab\",\r\nIfNull(A1.\"U_" +
            "SEI_FEDescu\",\'\') as \"codigoDescuentoLin\", A1.\"PriceBefDi\"*(A1.\"DiscPrcnt\"/100) a" +
            "s \"descuentoLin\", A1.\"DiscPrcnt\" as \"porcentajeDescuentoLin\",\r\nA0.\"DocNum\" as \"c" +
            "onsecutivofacturamodificada\", IfNull(A3.\"BeginStr\",\'\') as \"prefijoFacturaModific" +
            "ada\", \'5\' as \"tipoDocumentoFacturaModificada\"\r\nFrom \"OINV\" A0\r\nInner Join \"INV1\"" +
            " A1 On A0.\"DocEntry\" = A1.\"DocEntry\"\r\nInner Join \"OCRD\" A2 On A0.\"CardCode\" = A2" +
            ".\"CardCode\"\r\nInner Join \"NNM1\" A3 On A0.\"Series\" = A3.\"Series\"\r\nLeft Join \"@HBT_" +
            "MUNICIPIO\" A4 On A2.\"U_HBT_MunMed\" = A4.\"Code\"\r\nInner Join \"OCTG\" A5 On A0.\"Grou" +
            "pNum\" = A5.\"GroupNum\"\r\nLeft Join (Select \"DocEntry\", Sum(\"LineTotal\") as \"SubTot" +
            "al\" From \"INV1\" Group By \"DocEntry\") A6 On A0.\"DocEntry\" = A6.\"DocEntry\"\r\nLeft J" +
            "oin (Select \"DocEntry\", Sum(\"BaseSum\") as \"baseimpu\" From \"INV4\" Where IfNull(\"T" +
            "axSum\",0) != 0 Group By \"DocEntry\") A7 On A0.\"DocEntry\" = A7.\"DocEntry\"\r\nLeft Jo" +
            "in \"OADM\" A8 On 1 = 1\r\nLeft Join (Select \"Code\", STRING_AGG(\"U_Codigo\",\';\') As \"" +
            "string\" From \"@FEDIAN_SNRES\"\r\n\t\t\t\tGroup By \"Code\") A9 On A2.\"CardCode\" = A9.\"Cod" +
            "e\"\r\nLeft Join \"OITM\" A10 On A1.\"ItemCode\" = A10.\"ItemCode\"\r\nLeft Join \"INV4\" A11" +
            " On A1.\"DocEntry\" = A11.\"DocEntry\" And A1.\"LineNum\" = A11.\"LineNum\" And A11.\"Rel" +
            "ateType\" = \'1\'\r\nLeft Join \"OSTC\" A12 On A11.\"StcCode\" = A12.\"Code\"\r\nLeft Join \"O" +
            "CRY\" A13 On A2.\"Country\" = A13.\"Code\"\r\nLeft Join (\r\n\t\t\tSelect B0.\"AbsEntry\" , Su" +
            "m(B0.\"WTAmnt\") as \"TotalRet\"\r\n\t\t\tFrom \"INV5\" B0 \r\n\t\t\tInner Join \"OWHT\" B1 On B0." +
            "\"WTCode\" = B1.\"WTCode\" And B1.\"U_HBT_TipRet\" != 0\r\n\t\t\tGroup By B1.\"U_HBT_TipRet\"" +
            ", B0.\"AbsEntry\"\r\n\t\t  ) A14 On A0.\"DocEntry\" = A14.\"AbsEntry\"\r\nWhere A0.\"DocEntry" +
            "\" = {0} And A1.\"TreeType\" != \'I\';")]
        public string FacturaConti {
            get {
                return ((string)(this["FacturaConti"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select \'6\' as \"version\", \'3\' as \"tipodocumento\", \'1\' as \"codigoPlantillaPdf\", IfN" +
            "ull(A3.\"BeginStr\",\'\') as \"prefijo\", \r\nA0.\"U_SEI_FEConcepND\" as \"tiponota\", A0.\"D" +
            "ocNum\" as \"consecutivo\", A0.\"U_SEI_FETipOper\" as \"tipoOperacion\",\r\nTO_NVARCHAR(A" +
            "0.\"DocDate\", \'YYYY-MM-DD\') as \"fechafacturacion\", TO_NVARCHAR(A0.\"DocDueDate\", \'" +
            "YYYY-MM-DD\') as \"fechavencimiento\",\r\nCase When A0.\"DocCur\" = \'$\' Then \'COP\' Else" +
            " \'COP\' End \"moneda\", A6.\"SubTotal\" as \"totalimportebruto\", \r\nA7.\"baseimpu\" as \"t" +
            "otalbaseimponible\", (A6.\"SubTotal\" + A0.\"VatSum\") as \"totalbaseconimpuestos\",\r\nA" +
            "0.\"DiscSum\" as \"totalDescuento\", A0.\"DiscPrcnt\" as \"campoAdicional3\",\r\n\'TEXTO EN" +
            "CABEZADO\' as \"campoAdicional6\", \'COP\' as \"codigoMonedaCambio\",\r\nA2.\"U_SEI_FERegF" +
            "is\" \"regimen\",\r\nA0.\"DocTotal\" + IfNull(A14.\"TotalRet\",0) as \"totalfactura\", A0.\"" +
            "DpmAppl\" as \"pagoanticipado\",  A0.\"Comments\" as \"descripcion\",\r\nCase When A2.\"U_" +
            "HBT_TipEnt\" = \'1\' Then \'2\' When A2.\"U_HBT_TipEnt\" = \'2\' Then \'1\' Else \'1\' End \"t" +
            "ipopersona\",\r\nCase When A2.\"U_HBT_TipEnt\" = \'2\' Then IfNull(A2.\"CardName\",\'\') \r\n" +
            "Else IfNull(A2.\"U_HBT_Nombres\",\'\') || \' \' || IfNull(A2.\"U_HBT_Apellido1\",\'\') || " +
            "\' \' || IfNull(A2.\"U_HBT_Apellido2\",\'\') End \"nombreCompleto\",\r\nIfNull(A2.\"U_HBT_T" +
            "ipDoc\",\'\') as \"tipoidentificacion\",\r\nCase When IfNull(Locate(A2.\"LicTradNum\",\'-\'" +
            "),0) = 0 Then A2.\"LicTradNum\" Else SubString(A2.\"LicTradNum\", 1, Locate(A2.\"LicT" +
            "radNum\", \'-\')-1) End \"numeroidentificacion\",\r\nCase When Locate(A1.\"LicTradNum\",\'" +
            "-\') = 0 Then \'\' Else SubString(A0.\"LicTradNum\", (Locate(A0.\"LicTradNum\", \'-\')+1)" +
            ",1) End \"digitoverificacion\",\r\n\'SI\' as \"aplicafel\", \'EMAIL\' as \"envioPorEmailPla" +
            "taforma\", A2.\"E_Mail\" as \"email\", \r\nA2.\"Country\" as \"pais\", A13.\"Name\" as \"paisn" +
            "ombre\",\r\nSUBSTRING(A2.\"U_HBT_MunMed\",1,2) as \"departamento\", A4.\"U_NomDepartamen" +
            "to\" as \"nombredepartamento\",\r\nA2.\"U_HBT_MunMed\" as \"codigoCiudad\", A4.\"Name\" as " +
            "\"descripcionCiudad\",\r\nA2.\"Address\" as \"direccion\", A2.\"Phone1\" as \"telefono\", Ca" +
            "se When A0.\"GroupNum\" = \'-1\' Then \'1\' Else \'2\' End \"tipocompra\",\r\nA2.\"BillToDef\"" +
            " as \"despachadoANombre\", A2.\"Phone1\" as \"telefonoEntrega\", A2.\"Address\" as \"dire" +
            "ccionEntrega\", A2.\"Country\" as \"paisEntrega\",\r\nCase When A0.\"DocType\" = \'S\' Then" +
            " A1.\"AcctCode\" Else A1.\"ItemCode\" End as \"codigoproducto\", \r\nA10.\"U_SEI_FEIdent\"" +
            " as \"tipocodigoproducto\",\r\nA1.\"Dscription\" as \"referencia\", A1.\"Dscription\" as \"" +
            "descripcionLine\", A1.\"Dscription\" as \"nombreProducto\", \r\nCase When A0.\"DocType\" " +
            "= \'S\' Then 1 Else Cast(A1.\"Quantity\" as decimal(28,8)) End as \"cantidad\",\r\nCASE " +
            "\r\nWHEN IfNull(A1.\"UomCode\",\'\') = \'Manual\' Then (Select IfNull(P0.\"U_DIAN_UM\",\'\')" +
            " From \"@FEDIAN_HOMOL_UM\" P0 Where P0.\"U_SAP_UM\" = A1.\"unitMsr\") \r\nElse (Select I" +
            "fNull(P0.\"U_DIAN_UM\",\'\') From \"@FEDIAN_HOMOL_UM\" P0 Where P0.\"U_SAP_UM\" = A1.\"Uo" +
            "mCode\") End \"unidadmedida\", \r\nA1.\"PriceBefDi\" as \"valorunitario\", \r\nA1.\"LineTota" +
            "l\" as \"preciosinimpuestos\", \r\nA1.\"LineTotal\" as \"preciototal\", Cast(A1.\"DiscPrcn" +
            "t\" as decimal(28,8)) as \"porcentajedescuento\",\r\nA0.\"U_SEI_FEMedPago\" as \"medioPa" +
            "go\", A5.\"PymntGroup\" as \"nombreCondPago\", A0.\"U_CuidadEmi\" as \"documentoEmitidoE" +
            "n\",\r\nCase When A0.\"GroupNum\" = \'-1\' Then \'1\' Else A5.\"ExtraMonth\"*30 + A5.\"Extra" +
            "Days\" End \"periododepagoa\",\r\nCase\r\nWhen A1.\"TaxCode\" = \'IVAEXENT\' Then \'3\'\r\nWhen" +
            " A1.\"TaxCode\" = \'IVAGEV0\' Then \'2\'\r\nWhen A1.\"TaxCode\" = \'IVANOGRV\' Then \'2\'\r\nEls" +
            "e \'1\' End \"tipoImpuesto\", \r\nA12.\"U_SEI_FETributo\" as \"codigoImpuestoRetencion\", " +
            "Cast(A11.\"TaxRate\" as decimal(28,8)) as \"porcentaje\",\r\nA11.\"TaxSum\" as \"valorImp" +
            "uestoRetencion\", Case When IfNull(A11.\"TaxSum\",0) = 0 Then 0 Else A11.\"BaseSum\" " +
            "End as \"baseimponible\",\r\n\'false\' as \"isAutoRetenido\", IfNull(A9.\"string\",\'ZZ\') a" +
            "s \"tipoobligacion\",\r\nIfNull(A0.\"U_SEI_FEDescu\",\'\') as \"codigoDescuentoCab\", A0.\"" +
            "DiscSum\" as \"descuentoCab\", A0.\"DiscPrcnt\" as \"porcentajeDescuentoCab\",\r\nIfNull(" +
            "A1.\"U_SEI_FEDescu\",\'\') as \"codigoDescuentoLin\", A1.\"PriceBefDi\"*(A1.\"DiscPrcnt\"/" +
            "100) as \"descuentoLin\", A1.\"DiscPrcnt\" as \"porcentajeDescuentoLin\"\r\nFrom \"OINV\" " +
            "A0\r\nInner Join \"INV1\" A1 On A0.\"DocEntry\" = A1.\"DocEntry\"\r\nInner Join \"OCRD\" A2 " +
            "On A0.\"CardCode\" = A2.\"CardCode\"\r\nInner Join \"NNM1\" A3 On A0.\"Series\" = A3.\"Seri" +
            "es\"\r\nLeft Join \"@HBT_MUNICIPIO\" A4 On A2.\"U_HBT_MunMed\" = A4.\"Code\"\r\nInner Join " +
            "\"OCTG\" A5 On A0.\"GroupNum\" = A5.\"GroupNum\"\r\nLeft Join (Select \"DocEntry\", Sum(\"L" +
            "ineTotal\") as \"SubTotal\" From \"INV1\" Group By \"DocEntry\") A6 On A0.\"DocEntry\" = " +
            "A6.\"DocEntry\"\r\nLeft Join (Select \"DocEntry\", Sum(\"BaseSum\") as \"baseimpu\" From \"" +
            "INV4\" Where IfNull(\"TaxSum\",0) != 0 Group By \"DocEntry\") A7 On A0.\"DocEntry\" = A" +
            "7.\"DocEntry\"\r\nLeft Join \"OADM\" A8 On 1 = 1\r\nLeft Join (Select \"Code\", STRING_AGG" +
            "(\"U_Codigo\",\';\') As \"string\" From \"@FEDIAN_SNRES\"\r\n\t\t\t\tGroup By \"Code\") A9 On A2" +
            ".\"CardCode\" = A9.\"Code\"\r\nLeft Join \"OITM\" A10 On A1.\"ItemCode\" = A10.\"ItemCode\"\r" +
            "\nLeft Join \"INV4\" A11 On A1.\"DocEntry\" = A11.\"DocEntry\" And A1.\"LineNum\" = A11.\"" +
            "LineNum\" And A11.\"RelateType\" = \'1\'\r\nLeft Join \"OSTC\" A12 On A11.\"StcCode\" = A12" +
            ".\"Code\"\r\nLeft Join \"OCRY\" A13 On A2.\"Country\" = A13.\"Code\"\r\nLeft Join (\r\n\t\t\tSele" +
            "ct B0.\"AbsEntry\" , Sum(B0.\"WTAmnt\") as \"TotalRet\"\r\n\t\t\tFrom \"INV5\" B0 \r\n\t\t\tInner " +
            "Join \"OWHT\" B1 On B0.\"WTCode\" = B1.\"WTCode\" And B1.\"U_HBT_TipRet\" != 0\r\n\t\t\tGroup" +
            " By B1.\"U_HBT_TipRet\", B0.\"AbsEntry\"\r\n\t\t  ) A14 On A0.\"DocEntry\" = A14.\"AbsEntry" +
            "\"\r\nWhere A0.\"DocEntry\" = {0} And A1.\"TreeType\" != \'I\';")]
        public string NotaDebito {
            get {
                return ((string)(this["NotaDebito"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select * From [@FEDIAN_INTERF_ERR] Where IsNull(Cast(U_MsgExter as Nvarchar(2500)" +
            "), \'\') = \'{0}\'")]
        public string Msginter {
            get {
                return ((string)(this["Msginter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select * from \"@FEDIAN_CODDOC\" Order By \"Code\"")]
        public string cmbTipodoc {
            get {
                return ((string)(this["cmbTipodoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Select ""U_Status"", 
					Case 
					When ""U_Status"" = '1' Then 'Procesado' 
					When ""U_Status"" = '2' Then 'En Proceso' 
					When ""U_Status"" = '3' Then 'Error' 
					When ""U_Status"" = '10' Then 'Procesado'
					When ""U_Status"" = '102' Then 'Error'
					When ""U_Status"" = '106' Then 'Error' else 'En Proceso' End
					from ""@FEDIAN_MONITORLOG"" 
					Where IfNull(""U_Status"",'') != '' 
					Group By ""U_Status""
					Order By ""U_Status""")]
        public string cmbEstado {
            get {
                return ((string)(this["cmbEstado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Select A0.""Code"", A0.""U_DocNum"", A0.""U_Folio"", A0.""U_Prefijo"", A0.""U_DocType"", A0.""U_ObjType"", IfNull(Cast(A0.""U_Fecha_Envio"" as nvarchar(100)),'') as ""U_Fecha_Envio""
From ""@FEDIAN_MONITORLOG"" A0
Where IfNull(A0.""U_Status"",'') = '' or IfNull(A0.""U_Status"",'') In ({0})")]
        public string ReSendAuto {
            get {
                return ((string)(this["ReSendAuto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select IfNull(Max(cast(\"Code\" as Int)),0)+1 As \"NextCode\" From \"@FEDIAN_MONITORLO" +
            "G\"")]
        public string MaxLog {
            get {
                return ((string)(this["MaxLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Select 
A1.""U_SEI_FETributo"" ""codigoImpuestoRetencion"",
Cast(A0.""TaxRate"" as decimal(28,8)) as ""porcentaje"", Sum(A0.""TaxSum"") as ""valorImpuestoRetencion"", 
Sum(A0.""BaseSum"") as ""baseimponible"", 'false' as ""isAutoRetenido""
From ""INV4"" A0
Inner Join ""OSTC"" A1 On A0.""StcCode"" = A1.""Code""
Where A0.""DocEntry"" = {0} And A0.""RelateType"" = '1'
Group By A1.""U_SEI_FETributo"", A0.""TaxRate""

Union All

Select
A1.""U_SEI_FETributo"" ""codigoImpuestoRetencion"",
Cast(A1.""PrctBsAmnt"" as decimal(28,8)) as ""porcentaje"", Sum(A0.""WTAmnt"") as ""valorImpuestoRetencion"", Sum(A0.""U_HBT_BaseRet"") as ""baseimponible"",
'true' as ""isAutoRetenido""
From ""INV5"" A0 
Inner Join ""OWHT"" A1 On A0.""WTCode"" = A1.""WTCode""
Where A0.""AbsEntry"" = {0} And A1.""U_HBT_TipRet"" != 0
Group By A1.""U_SEI_FETributo"", A1.""PrctBsAmnt""")]
        public string impFac {
            get {
                return ((string)(this["impFac"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Select 
A1.""U_SEI_FETributo"" ""codigoImpuestoRetencion"",
Cast(A0.""TaxRate"" as decimal(28,8)) as ""porcentaje"", Sum(A0.""TaxSum"") as ""valorImpuestoRetencion"", 
Sum(A0.""BaseSum"") as ""baseimponible"", 'false' as ""isAutoRetenido""
From ""RIN4"" A0
Inner Join ""OSTC"" A1 On A0.""StcCode"" = A1.""Code""
Where A0.""DocEntry"" = {0} And A0.""RelateType"" = '1'
Group By A1.""U_SEI_FETributo"", A0.""TaxRate""

Union All

Select
A1.""U_SEI_FETributo"" ""codigoImpuestoRetencion"",
Cast(A1.""PrctBsAmnt"" as decimal(28,8)) as ""porcentaje"", Sum(A0.""WTAmnt"") as ""valorImpuestoRetencion"", Sum(A0.""U_HBT_BaseRet"") as ""baseimponible"",
'true' as ""isAutoRetenido""
From ""RIN5"" A0 
Inner Join ""OWHT"" A1 On A0.""WTCode"" = A1.""WTCode""
Where A0.""AbsEntry"" = {0} And A1.""U_HBT_TipRet"" != 0
Group By A1.""U_SEI_FETributo"", A1.""PrctBsAmnt""")]
        public string impNC {
            get {
                return ((string)(this["impNC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Select 
A1.""U_SEI_FETributo"" ""codigoImpuestoRetencion"",
Cast(A0.""TaxRate"" as decimal(28,8)) as ""porcentaje"", Sum(A0.""TaxSum"") as ""valorImpuestoRetencion"", 
Sum(A0.""BaseSum"") as ""baseimponible"", 'false' as ""isAutoRetenido""
From ""INV4"" A0
Inner Join ""OSTC"" A1 On A0.""StcCode"" = A1.""Code""
Where A0.""DocEntry"" = {0} And A0.""RelateType"" = '1'
Group By A1.""U_SEI_FETributo"", A0.""TaxRate""

Union All

Select
A1.""U_SEI_FETributo"" ""codigoImpuestoRetencion"",
Cast(A1.""PrctBsAmnt"" as decimal(28,8)) as ""porcentaje"", Sum(A0.""WTAmnt"") as ""valorImpuestoRetencion"", Sum(A0.""U_HBT_BaseRet"") as ""baseimponible"",
'true' as ""isAutoRetenido""
From ""INV5"" A0 
Inner Join ""OWHT"" A1 On A0.""WTCode"" = A1.""WTCode""
Where A0.""AbsEntry"" = {0} And A1.""U_HBT_TipRet"" != 0
Group By A1.""U_SEI_FETributo"", A1.""PrctBsAmnt""")]
        public string impND {
            get {
                return ((string)(this["impND"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select \'ENCABEZADOFE\' as \"nombreCampo\", \r\nA0.\"PrintHeadr\" || \';NIT: \' || A0.\"TaxI" +
            "dNum\" || \';\' || A0.\"U_SEI_LYFAC\" as \"valorCampo\", \r\n\'27B1\' as \"seccion\"\r\nFrom OA" +
            "DM A0\r\n\r\nUnion All\r\n\r\nSelect \'UBICACION\' as \"nombreCampo\", \r\n\'Oficinas: \' || IfN" +
            "ull(A1.\"Street\",\'\') || \';PBX: \' || IfNull(A0.\"Phone1\",\'\') || \';FAX: \' || \r\nIfNul" +
            "l(A0.\"Fax\",\'\') || \';Email: \' || IfNull(A0.\"E_Mail\",\'\') || \r\n\';\' || A2.\"Name\" || " +
            "\' - \' || A3.\"Name\" || \';\' || A1.\"IntrntAdrs\",\r\n\'27A3\' as \"seccion\"\r\nFrom OADM A0" +
            "\r\nInner Join ADM1 A1 ON A0.\"Code\" = A1.\"Code\"\r\nLeft Join \"@HBT_MUNICIPIO\" A2 On " +
            "A0.\"U_HBT_MunMed\" = A2.\"Code\"\r\nLeft Join OCRY A3 On A0.\"Country\" = A3.\"Code\"\r\n\r\n" +
            "Union All\r\n\r\nSelect \'OBSERVACIONES\' as \"nombreCampo\", \r\nA0.\"Comments\",\r\n\'27A2\' a" +
            "s \"seccion\"\r\nFrom OINV A0\r\nWhere A0.\"DocEntry\" = {0} And IfNull(A0.\"Comments\",\'\'" +
            ") != \'\'\r\n\r\nUnion All\r\n\r\nSelect \'totalapagar\' as \"nombreCampo\", \r\nCast(Cast(A0.\"D" +
            "ocTotal\" as Decimal(15,0)) as nvarchar(100)),\r\n\'\' as \"seccion\"\r\nFrom OINV A0\r\nWh" +
            "ere A0.\"DocEntry\" = {0}\r\n\r\nUnion All\r\n\r\nSelect \'documentoemitidoen\' as \"nombreCa" +
            "mpo\", \r\nCast(IfNull(A0.\"U_CuidadEmi\",\'\') as nvarchar(100)),\r\n\'\' as \"seccion\"\r\nFr" +
            "om OINV A0\r\nWhere A0.\"DocEntry\" = {0} And IfNull(A0.\"U_CuidadEmi\",\'\') != \'\'\r\n\r\nU" +
            "nion All\r\n\r\nSelect \'retencionsugerida\' as \"nombreCampo\", \r\n\'RETEFUENTE SUGERIDA:" +
            " $ \' || Cast(Cast(Sum(A0.\"WTAmnt\") as Decimal(15,0)) as nvarchar(100)),\r\n\'\' as \"" +
            "seccion\"\r\nFrom INV5 A0\r\nInner Join OWHT A1 On A0.\"WTCode\" = A1.\"WTCode\" and A1.\"" +
            "U_HBT_TipRet\" != 0\r\nWhere A0.\"AbsEntry\" = {0}\r\nhaving  Sum(A0.\"WTAmnt\") > 0\r\n\r\nU" +
            "nion All\r\n\r\nSelect \'subtotal\' as \"nombreCampo\",\r\nCast(Cast(Sum(A1.\"LineTotal\") -" +
            " A0.\"DiscSum\" as decimal(15,0)) as Nvarchar(100)),\r\n\'\' as \"seccion\"\r\nFrom OINV A" +
            "0\r\nInner Join INV1 A1 On A0.\"DocEntry\" = A1.\"DocEntry\"\r\nWhere A0.\"DocEntry\" = {0" +
            "}\r\nGroup By A0.\"DiscSum\", A0.\"DocEntry\"")]
        public string listaAdiFac {
            get {
                return ((string)(this["listaAdiFac"]));
            }
            set {
                this["listaAdiFac"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select \'ENCABEZADOFE\' as \"nombreCampo\", \r\nA0.\"PrintHeadr\" || \';NIT: \' || A0.\"TaxI" +
            "dNum\" as \"valorCampo\", \r\n\'27B5\' as \"seccion\"\r\nFrom OADM A0\r\n\r\nUnion All\r\n\r\nSelec" +
            "t \'UBICACION\' as \"nombreCampo\", \r\n\'Oficinas: \' || IfNull(A1.\"Street\",\'\') || \';PB" +
            "X: \' || IfNull(A0.\"Phone1\",\'\') || \';FAX: \' || \r\nIfNull(A0.\"Fax\",\'\') || \';Email: " +
            "\' || IfNull(A0.\"E_Mail\",\'\') || \r\n\';\' || A2.\"Name\" || \' - \' || A3.\"Name\" || \';\' |" +
            "| A1.\"IntrntAdrs\",\r\n\'27A3\' as \"seccion\"\r\nFrom OADM A0\r\nInner Join ADM1 A1 ON A0." +
            "\"Code\" = A1.\"Code\"\r\nLeft Join \"@HBT_MUNICIPIO\" A2 On A0.\"U_HBT_MunMed\" = A2.\"Cod" +
            "e\"\r\nLeft Join OCRY A3 On A0.\"Country\" = A3.\"Code\"\r\n\r\nUnion All\r\n\r\nSelect \'OBSERV" +
            "ACIONES\' as \"nombreCampo\", \r\nA0.\"Comments\",\r\n\'27A2\' as \"seccion\"\r\nFrom ORIN A0\r\n" +
            "Where A0.\"DocEntry\" = 128416 And IfNull(A0.\"Comments\",\'\') != \'\'\r\n\r\nUnion All\r\n\r\n" +
            "Select \'TIPO NOTA\' as \"nombreCampo\", \r\nA0.\"U_SEI_FEConcepNC\" as \"valorCampo\",\r\n\'" +
            "27B6\' as \"seccion\"\r\nFrom ORIN A0\r\nWhere A0.\"DocEntry\" = {0}\r\n\r\nUnion All\r\n\r\nSele" +
            "ct \'documentoemitidoen\' as \"nombreCampo\", \r\nCast(IfNull(A0.\"U_CuidadEmi\",\'\') as " +
            "nvarchar(100)),\r\n\'\' as \"seccion\"\r\nFrom ORIN A0\r\nWhere A0.\"DocEntry\" = {0} And If" +
            "Null(A0.\"U_CuidadEmi\",\'\') != \'\'\r\n\r\nUnion All\r\n\r\nSelect \'totalapagar\' as \"nombreC" +
            "ampo\", \r\nCast(Cast(A0.\"DocTotal\" as Decimal(15,2)) as nvarchar(100)),\r\n\'\' as \"se" +
            "ccion\"\r\nFrom ORIN A0\r\nWhere A0.\"DocEntry\" = {0}\r\n\r\nUnion All\r\n\r\nSelect \'retencio" +
            "nsugerida\' as \"nombreCampo\", \r\n\'RETEFUENTE SUGERIDA:\' || Cast(Cast(Sum(A0.\"WTAmn" +
            "t\") as Decimal(15,2)) as nvarchar(100)),\r\n\'\' as \"seccion\"\r\nFrom RIN5 A0\r\nInner J" +
            "oin OWHT A1 On A0.\"WTCode\" = A1.\"WTCode\" and A1.\"U_HBT_TipRet\" != 0\r\nWhere A0.\"A" +
            "bsEntry\" = {0}\r\nhaving  Sum(A0.\"WTAmnt\") > 0\r\n\r\nUnion All\r\n\r\nSelect \'subtotal\' a" +
            "s \"nombreCampo\",\r\nCast(Cast(Sum(A1.\"LineTotal\") - A0.\"DiscSum\" as decimal(15,0))" +
            " as Nvarchar(100)),\r\n\'\' as \"seccion\"\r\nFrom ORIN A0\r\nInner Join RIN1 A1 On A0.\"Do" +
            "cEntry\" = A1.\"DocEntry\"\r\nWhere A0.\"DocEntry\" = {0}\r\nGroup By A0.\"DiscSum\", A0.\"D" +
            "ocEntry\"")]
        public string listaAdiNC {
            get {
                return ((string)(this["listaAdiNC"]));
            }
            set {
                this["listaAdiNC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select \'ENCABEZADOFE\' as \"nombreCampo\", \r\nA0.\"PrintHeadr\" || \';NIT: \' || A0.\"TaxI" +
            "dNum\" as \"valorCampo\", \r\n\'27B5\' as \"seccion\"\r\nFrom OADM A0\r\n\r\nUnion All\r\n\r\nSelec" +
            "t \'UBICACION\' as \"nombreCampo\", \r\n\'Oficinas: \' || IfNull(A1.\"Street\",\'\') || \';PB" +
            "X: \' || IfNull(A0.\"Phone1\",\'\') || \';FAX: \' || \r\nIfNull(A0.\"Fax\",\'\') || \';Email: " +
            "\' || IfNull(A0.\"E_Mail\",\'\') || \r\n\';\' || A2.\"Name\" || \' - \' || A3.\"Name\" || \';\' |" +
            "| A1.\"IntrntAdrs\",\r\n\'27A3\' as \"seccion\"\r\nFrom OADM A0\r\nInner Join ADM1 A1 ON A0." +
            "\"Code\" = A1.\"Code\"\r\nLeft Join \"@HBT_MUNICIPIO\" A2 On A0.\"U_HBT_MunMed\" = A2.\"Cod" +
            "e\"\r\nLeft Join OCRY A3 On A0.\"Country\" = A3.\"Code\"\r\n\r\n\r\nUnion All\r\n\r\nSelect \'OBSE" +
            "RVACIONES\' as \"nombreCampo\", \r\nA0.\"Comments\",\r\n\'27A2\' as \"seccion\"\r\nFrom OINV A0" +
            "\r\nWhere A0.\"DocEntry\" = 128416 And IfNull(A0.\"Comments\",\'\') != \'\'\r\n\r\nUnion All\r\n" +
            "\r\nSelect \'TIPO NOTA\' as \"nombreCampo\", \r\nA0.\"U_SEI_FEConcepND\" as \"valorCampo\",\r" +
            "\n\'27B6\' as \"seccion\"\r\nFrom OINV A0\r\nWhere A0.\"DocEntry\" = {0}\r\n\r\nUnion All\r\n\r\nSe" +
            "lect \'documentoemitidoen\' as \"nombreCampo\", \r\nCast(IfNull(A0.\"U_CuidadEmi\",\'\') a" +
            "s nvarchar(100)),\r\n\'\' as \"seccion\"\r\nFrom OINV A0\r\nWhere A0.\"DocEntry\" = {0} And " +
            "IfNull(A0.\"U_CuidadEmi\",\'\') != \'\'\r\n\r\nUnion All\r\n\r\nSelect \'totalapagar\' as \"nombr" +
            "eCampo\", \r\nCast(Cast(A0.\"DocTotal\" as Decimal (15,2)) as nvarchar(100)),\r\n\'\' as " +
            "\"seccion\"\r\nFrom OINV A0\r\nWhere A0.\"DocEntry\" = {0}\r\n\r\nUnion All\r\n\r\nSelect \'reten" +
            "cionsugerida\' as \"nombreCampo\", \r\n\'RETEFUENTE SUGERIDA: $ \' || Cast(Cast(Sum(A0." +
            "\"WTAmnt\") as Decimal(15,0)) as nvarchar(100)),\r\n\'\' as \"seccion\"\r\nFrom INV5 A0\r\nI" +
            "nner Join OWHT A1 On A0.\"WTCode\" = A1.\"WTCode\" and A1.\"U_HBT_TipRet\" != 0\r\nWhere" +
            " A0.\"AbsEntry\" = {0}\r\nhaving  Sum(A0.\"WTAmnt\") > 0\r\n\r\nUnion All\r\n\r\nSelect \'subto" +
            "tal\' as \"nombreCampo\",\r\nCast(Cast(Sum(A1.\"LineTotal\") - A0.\"DiscSum\" as decimal(" +
            "15,0)) as Nvarchar(100)),\r\n\'\' as \"seccion\"\r\nFrom OINV A0\r\nInner Join INV1 A1 On " +
            "A0.\"DocEntry\" = A1.\"DocEntry\"\r\nWhere A0.\"DocEntry\" = {0}\r\nGroup By A0.\"DiscSum\"," +
            " A0.\"DocEntry\"")]
        public string listaAdiND {
            get {
                return ((string)(this["listaAdiND"]));
            }
            set {
                this["listaAdiND"] = value;
            }
        }
    }
}
