//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddOn_FE_DIAN.consultarEstadoDispape {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wsconsultaestadofactura.webservice.dispapeles.com/", ConfigurationName="consultarEstadoDispape.ConsultarEstado")]
    public interface ConsultarEstado {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://wsconsultaestadofactura.webservice.dispapeles.com/ConsultarEstado/consulta" +
            "rEstadoRequest", ReplyAction="http://wsconsultaestadofactura.webservice.dispapeles.com/ConsultarEstado/consulta" +
            "rEstadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AddOn_FE_DIAN.consultarEstadoDispape.consultarEstadoResponse consultarEstado(AddOn_FE_DIAN.consultarEstadoDispape.consultarEstadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsconsultaestadofactura.webservice.dispapeles.com/ConsultarEstado/consulta" +
            "rEstadoRequest", ReplyAction="http://wsconsultaestadofactura.webservice.dispapeles.com/ConsultarEstado/consulta" +
            "rEstadoResponse")]
        System.Threading.Tasks.Task<AddOn_FE_DIAN.consultarEstadoDispape.consultarEstadoResponse> consultarEstadoAsync(AddOn_FE_DIAN.consultarEstadoDispape.consultarEstadoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsconsultaestadofactura.webservice.dispapeles.com/")]
    public partial class felConsultaFactura : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long consecutivoField;
        
        private bool consecutivoFieldSpecified;
        
        private string contraseniaField;
        
        private long idEmpresaField;
        
        private bool idEmpresaFieldSpecified;
        
        private string prefijoField;
        
        private string tipoDocumentoField;
        
        private string tokenField;
        
        private string usuarioField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long consecutivo {
            get {
                return this.consecutivoField;
            }
            set {
                this.consecutivoField = value;
                this.RaisePropertyChanged("consecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool consecutivoSpecified {
            get {
                return this.consecutivoFieldSpecified;
            }
            set {
                this.consecutivoFieldSpecified = value;
                this.RaisePropertyChanged("consecutivoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                this.contraseniaField = value;
                this.RaisePropertyChanged("contrasenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                this.idEmpresaField = value;
                this.RaisePropertyChanged("idEmpresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEmpresaSpecified {
            get {
                return this.idEmpresaFieldSpecified;
            }
            set {
                this.idEmpresaFieldSpecified = value;
                this.RaisePropertyChanged("idEmpresaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string prefijo {
            get {
                return this.prefijoField;
            }
            set {
                this.prefijoField = value;
                this.RaisePropertyChanged("prefijo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsconsultaestadofactura.webservice.dispapeles.com/")]
    public partial class felMensajesProceso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoMensajeField;
        
        private string descripcionMensajeField;
        
        private string rechazoNotificacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoMensaje {
            get {
                return this.codigoMensajeField;
            }
            set {
                this.codigoMensajeField = value;
                this.RaisePropertyChanged("codigoMensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcionMensaje {
            get {
                return this.descripcionMensajeField;
            }
            set {
                this.descripcionMensajeField = value;
                this.RaisePropertyChanged("descripcionMensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string rechazoNotificacion {
            get {
                return this.rechazoNotificacionField;
            }
            set {
                this.rechazoNotificacionField = value;
                this.RaisePropertyChanged("rechazoNotificacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsconsultaestadofactura.webservice.dispapeles.com/")]
    public partial class felRespuestaEstado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoQrField;
        
        private int codigoUltimoEstadoAdquirenteField;
        
        private int codigoUltimoEstadoDianField;
        
        private int codigoUltimoEstadoDispapelesField;
        
        private int codigoUltimoEstadoEmailField;
        
        private long consecutivoField;
        
        private bool consecutivoFieldSpecified;
        
        private string cufeField;
        
        private string descripcionUltimoEstadoAdquirenteField;
        
        private string descripcionUltimoEstadoDianField;
        
        private string descripcionUltimoEstadoDispapelesField;
        
        private string descripcionUltimoEstadoEmailField;
        
        private int estadoProcesoField;
        
        private System.DateTime fechaFacturaField;
        
        private bool fechaFacturaFieldSpecified;
        
        private System.DateTime fechaRespuestaField;
        
        private bool fechaRespuestaFieldSpecified;
        
        private System.DateTime fechaRespuestaUltimoEstadoAdquirenteField;
        
        private bool fechaRespuestaUltimoEstadoAdquirenteFieldSpecified;
        
        private System.DateTime fechaRespuestaUltimoEstadoDianField;
        
        private bool fechaRespuestaUltimoEstadoDianFieldSpecified;
        
        private System.DateTime fechaRespuestaUltimoEstadoDispapelesField;
        
        private bool fechaRespuestaUltimoEstadoDispapelesFieldSpecified;
        
        private System.DateTime fechaRespuestaUltimoEstadoEmailField;
        
        private bool fechaRespuestaUltimoEstadoEmailFieldSpecified;
        
        private string firmaDelDocumentoField;
        
        private string idErpField;
        
        private string idLoteField;
        
        private felMensajesProceso[] listaMensajesProcesoField;
        
        private string prefijoField;
        
        private string selloDeValidacionField;
        
        private string tipoDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoQr {
            get {
                return this.codigoQrField;
            }
            set {
                this.codigoQrField = value;
                this.RaisePropertyChanged("codigoQr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoUltimoEstadoAdquirente {
            get {
                return this.codigoUltimoEstadoAdquirenteField;
            }
            set {
                this.codigoUltimoEstadoAdquirenteField = value;
                this.RaisePropertyChanged("codigoUltimoEstadoAdquirente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int codigoUltimoEstadoDian {
            get {
                return this.codigoUltimoEstadoDianField;
            }
            set {
                this.codigoUltimoEstadoDianField = value;
                this.RaisePropertyChanged("codigoUltimoEstadoDian");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codigoUltimoEstadoDispapeles {
            get {
                return this.codigoUltimoEstadoDispapelesField;
            }
            set {
                this.codigoUltimoEstadoDispapelesField = value;
                this.RaisePropertyChanged("codigoUltimoEstadoDispapeles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int codigoUltimoEstadoEmail {
            get {
                return this.codigoUltimoEstadoEmailField;
            }
            set {
                this.codigoUltimoEstadoEmailField = value;
                this.RaisePropertyChanged("codigoUltimoEstadoEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long consecutivo {
            get {
                return this.consecutivoField;
            }
            set {
                this.consecutivoField = value;
                this.RaisePropertyChanged("consecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool consecutivoSpecified {
            get {
                return this.consecutivoFieldSpecified;
            }
            set {
                this.consecutivoFieldSpecified = value;
                this.RaisePropertyChanged("consecutivoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string cufe {
            get {
                return this.cufeField;
            }
            set {
                this.cufeField = value;
                this.RaisePropertyChanged("cufe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string descripcionUltimoEstadoAdquirente {
            get {
                return this.descripcionUltimoEstadoAdquirenteField;
            }
            set {
                this.descripcionUltimoEstadoAdquirenteField = value;
                this.RaisePropertyChanged("descripcionUltimoEstadoAdquirente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string descripcionUltimoEstadoDian {
            get {
                return this.descripcionUltimoEstadoDianField;
            }
            set {
                this.descripcionUltimoEstadoDianField = value;
                this.RaisePropertyChanged("descripcionUltimoEstadoDian");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string descripcionUltimoEstadoDispapeles {
            get {
                return this.descripcionUltimoEstadoDispapelesField;
            }
            set {
                this.descripcionUltimoEstadoDispapelesField = value;
                this.RaisePropertyChanged("descripcionUltimoEstadoDispapeles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string descripcionUltimoEstadoEmail {
            get {
                return this.descripcionUltimoEstadoEmailField;
            }
            set {
                this.descripcionUltimoEstadoEmailField = value;
                this.RaisePropertyChanged("descripcionUltimoEstadoEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int estadoProceso {
            get {
                return this.estadoProcesoField;
            }
            set {
                this.estadoProcesoField = value;
                this.RaisePropertyChanged("estadoProceso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public System.DateTime fechaFactura {
            get {
                return this.fechaFacturaField;
            }
            set {
                this.fechaFacturaField = value;
                this.RaisePropertyChanged("fechaFactura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFacturaSpecified {
            get {
                return this.fechaFacturaFieldSpecified;
            }
            set {
                this.fechaFacturaFieldSpecified = value;
                this.RaisePropertyChanged("fechaFacturaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public System.DateTime fechaRespuesta {
            get {
                return this.fechaRespuestaField;
            }
            set {
                this.fechaRespuestaField = value;
                this.RaisePropertyChanged("fechaRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRespuestaSpecified {
            get {
                return this.fechaRespuestaFieldSpecified;
            }
            set {
                this.fechaRespuestaFieldSpecified = value;
                this.RaisePropertyChanged("fechaRespuestaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public System.DateTime fechaRespuestaUltimoEstadoAdquirente {
            get {
                return this.fechaRespuestaUltimoEstadoAdquirenteField;
            }
            set {
                this.fechaRespuestaUltimoEstadoAdquirenteField = value;
                this.RaisePropertyChanged("fechaRespuestaUltimoEstadoAdquirente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRespuestaUltimoEstadoAdquirenteSpecified {
            get {
                return this.fechaRespuestaUltimoEstadoAdquirenteFieldSpecified;
            }
            set {
                this.fechaRespuestaUltimoEstadoAdquirenteFieldSpecified = value;
                this.RaisePropertyChanged("fechaRespuestaUltimoEstadoAdquirenteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public System.DateTime fechaRespuestaUltimoEstadoDian {
            get {
                return this.fechaRespuestaUltimoEstadoDianField;
            }
            set {
                this.fechaRespuestaUltimoEstadoDianField = value;
                this.RaisePropertyChanged("fechaRespuestaUltimoEstadoDian");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRespuestaUltimoEstadoDianSpecified {
            get {
                return this.fechaRespuestaUltimoEstadoDianFieldSpecified;
            }
            set {
                this.fechaRespuestaUltimoEstadoDianFieldSpecified = value;
                this.RaisePropertyChanged("fechaRespuestaUltimoEstadoDianSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public System.DateTime fechaRespuestaUltimoEstadoDispapeles {
            get {
                return this.fechaRespuestaUltimoEstadoDispapelesField;
            }
            set {
                this.fechaRespuestaUltimoEstadoDispapelesField = value;
                this.RaisePropertyChanged("fechaRespuestaUltimoEstadoDispapeles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRespuestaUltimoEstadoDispapelesSpecified {
            get {
                return this.fechaRespuestaUltimoEstadoDispapelesFieldSpecified;
            }
            set {
                this.fechaRespuestaUltimoEstadoDispapelesFieldSpecified = value;
                this.RaisePropertyChanged("fechaRespuestaUltimoEstadoDispapelesSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public System.DateTime fechaRespuestaUltimoEstadoEmail {
            get {
                return this.fechaRespuestaUltimoEstadoEmailField;
            }
            set {
                this.fechaRespuestaUltimoEstadoEmailField = value;
                this.RaisePropertyChanged("fechaRespuestaUltimoEstadoEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRespuestaUltimoEstadoEmailSpecified {
            get {
                return this.fechaRespuestaUltimoEstadoEmailFieldSpecified;
            }
            set {
                this.fechaRespuestaUltimoEstadoEmailFieldSpecified = value;
                this.RaisePropertyChanged("fechaRespuestaUltimoEstadoEmailSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string firmaDelDocumento {
            get {
                return this.firmaDelDocumentoField;
            }
            set {
                this.firmaDelDocumentoField = value;
                this.RaisePropertyChanged("firmaDelDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string idErp {
            get {
                return this.idErpField;
            }
            set {
                this.idErpField = value;
                this.RaisePropertyChanged("idErp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string idLote {
            get {
                return this.idLoteField;
            }
            set {
                this.idLoteField = value;
                this.RaisePropertyChanged("idLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaMensajesProceso", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=21)]
        public felMensajesProceso[] listaMensajesProceso {
            get {
                return this.listaMensajesProcesoField;
            }
            set {
                this.listaMensajesProcesoField = value;
                this.RaisePropertyChanged("listaMensajesProceso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string prefijo {
            get {
                return this.prefijoField;
            }
            set {
                this.prefijoField = value;
                this.RaisePropertyChanged("prefijo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string selloDeValidacion {
            get {
                return this.selloDeValidacionField;
            }
            set {
                this.selloDeValidacionField = value;
                this.RaisePropertyChanged("selloDeValidacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarEstado", WrapperNamespace="http://wsconsultaestadofactura.webservice.dispapeles.com/", IsWrapped=true)]
    public partial class consultarEstadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsconsultaestadofactura.webservice.dispapeles.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AddOn_FE_DIAN.consultarEstadoDispape.felConsultaFactura felConsultaFactura;
        
        public consultarEstadoRequest() {
        }
        
        public consultarEstadoRequest(AddOn_FE_DIAN.consultarEstadoDispape.felConsultaFactura felConsultaFactura) {
            this.felConsultaFactura = felConsultaFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarEstadoResponse", WrapperNamespace="http://wsconsultaestadofactura.webservice.dispapeles.com/", IsWrapped=true)]
    public partial class consultarEstadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsconsultaestadofactura.webservice.dispapeles.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AddOn_FE_DIAN.consultarEstadoDispape.felRespuestaEstado @return;
        
        public consultarEstadoResponse() {
        }
        
        public consultarEstadoResponse(AddOn_FE_DIAN.consultarEstadoDispape.felRespuestaEstado @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultarEstadoChannel : AddOn_FE_DIAN.consultarEstadoDispape.ConsultarEstado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarEstadoClient : System.ServiceModel.ClientBase<AddOn_FE_DIAN.consultarEstadoDispape.ConsultarEstado>, AddOn_FE_DIAN.consultarEstadoDispape.ConsultarEstado {
        
        public ConsultarEstadoClient() {
        }
        
        public ConsultarEstadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultarEstadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarEstadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarEstadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AddOn_FE_DIAN.consultarEstadoDispape.consultarEstadoResponse AddOn_FE_DIAN.consultarEstadoDispape.ConsultarEstado.consultarEstado(AddOn_FE_DIAN.consultarEstadoDispape.consultarEstadoRequest request) {
            return base.Channel.consultarEstado(request);
        }
        
        public AddOn_FE_DIAN.consultarEstadoDispape.felRespuestaEstado consultarEstado(AddOn_FE_DIAN.consultarEstadoDispape.felConsultaFactura felConsultaFactura) {
            AddOn_FE_DIAN.consultarEstadoDispape.consultarEstadoRequest inValue = new AddOn_FE_DIAN.consultarEstadoDispape.consultarEstadoRequest();
            inValue.felConsultaFactura = felConsultaFactura;
            AddOn_FE_DIAN.consultarEstadoDispape.consultarEstadoResponse retVal = ((AddOn_FE_DIAN.consultarEstadoDispape.ConsultarEstado)(this)).consultarEstado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AddOn_FE_DIAN.consultarEstadoDispape.consultarEstadoResponse> AddOn_FE_DIAN.consultarEstadoDispape.ConsultarEstado.consultarEstadoAsync(AddOn_FE_DIAN.consultarEstadoDispape.consultarEstadoRequest request) {
            return base.Channel.consultarEstadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AddOn_FE_DIAN.consultarEstadoDispape.consultarEstadoResponse> consultarEstadoAsync(AddOn_FE_DIAN.consultarEstadoDispape.felConsultaFactura felConsultaFactura) {
            AddOn_FE_DIAN.consultarEstadoDispape.consultarEstadoRequest inValue = new AddOn_FE_DIAN.consultarEstadoDispape.consultarEstadoRequest();
            inValue.felConsultaFactura = felConsultaFactura;
            return ((AddOn_FE_DIAN.consultarEstadoDispape.ConsultarEstado)(this)).consultarEstadoAsync(inValue);
        }
    }
}
