//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddOn_FE_DIAN {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Querys : global::System.Configuration.ApplicationSettingsBase {
        
        private static Querys defaultInstance = ((Querys)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Querys())));
        
        public static Querys Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select Cadena from (\r\nSelect 0 \'LineNum\', 1 as \'ordenplano\', Cadena from (\r\n\r\nSel" +
            "ect \'ENC\' + \',\' + \'NC\' + \',\' + \r\nCase When CharIndex(\'-\', A2.TaxIdNum) = 0 Then " +
            "A2.TaxIdNum Else SubString(A2.TaxIdNum, 1, CharIndex(\'-\', A2.TaxIdNum)-1) End + " +
            "\',\' + \r\nCase when CharIndex(\'-\', A1.LicTradNum) = 0 Then A1.LicTradNum Else SubS" +
            "tring(A1.LicTradNum, 1, CharIndex(\'-\', A1.LicTradNum)-1) End \r\n+ \',\' + \'UBL 2.1\'" +
            " + \',\' + \'DIAN 2.1\' + \',\' + IsNull(A4.BeginStr,\'\') + Cast(A0.DocNum as Nvarchar(" +
            "100)) + \',\' \r\n+ Convert(char(10), A0.DocDate,126) + \',\' + Convert(varchar(10), G" +
            "etDate(), 108)+ \'-05:00\' + \',\' + IsNull(A6.U_DocDIAN,\'\') + \',\'  +\r\nCase When A0." +
            "DocCur = \'$\' Then \'COP\' Else A0.DocCur End + \',\' + \'\' + \',\' + \'\' + \',\' +\r\n\'\' + \'" +
            ",\' + \'\' + \',\' + Cast(A5.NLineas as Nvarchar(5)) + \',\' + Convert(char(10), A0.Doc" +
            "DueDate,126) + \',\' + \r\n\'\' + \',\' + \'\' + \',\' + \'\' + \',\' + Substring(IsNull(A3.U_Am" +
            "biente,\'2\'),2,2) + \',\' + IsNull(A0.U_SEI_FETipOper,\'\') + \',\' + \'\' As \'Cadena\'\r\nF" +
            "rom ORIN A0 \r\nInner Join OCRD A1 On A0.CardCode = A1.CardCode \r\nInner Join OADM " +
            "A2 on 1 = 1\r\nLeft Join [@FEDIAN_PARAMG] A3 On 1 = 1\r\nLeft Join NNM1 A4 On A0.Ser" +
            "ies = A4.Series\r\nLeft Join (Select DocEntry, Count(*) \'NLineas\' From RIN1 Group " +
            "By DocEntry) A5 On A0.DocEntry = A5.DocEntry\r\nLeft Join \"@FEDIAN_NUMAUTORI\" A6 O" +
            "n A0.Series = A6.Code\r\nWhere A0.DocEntry = {0}\r\n\r\nUnion All \r\n\r\nSelect \'EMI\' + \'" +
            ",\' + \r\nCase When IsNull(A0.U_HBT_TipEnt,\'\') = \'1\' Then \'2\' Else \'1\' End + \',\' + " +
            "\r\nCase When CharIndex(\'-\', A0.TaxIdNum) = 0 Then A0.TaxIdNum Else SubString(A0.T" +
            "axIdNum, 1, CharIndex(\'-\', A0.TaxIdNum)-1) End + \',\' +\r\nIsNull(U_SEI_FETipDoc,\'\'" +
            ") + \',\' + \'48\' + \',\' + \'\' + \',\' + IsNull(A0.PrintHeadr,\'\') + \',\' + \r\nIsNull(A0.P" +
            "rintHeadr,\'\') + \',\' + \'\' + \',\' + \'\' + \',\' + IsNull(A1.Street,\'\') + \',\' + IsNull(" +
            "Substring(A0.U_HBT_MunMed,1,2),\'\') \r\n+ \',\' + \'\' + \',\' + IsNull(A2.Name,\'\') + \',\'" +
            " + \'\' + \',\' +\r\nIsNull(A1.Country,\'\') + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + Is" +
            "Null(A2.U_NomDepartamento,\'\') + \',\' + \'\' + \',\' + IsNull(A3.Name,\'\') + \',\' +\r\nCas" +
            "e When CharIndex(\'-\', A0.TaxIdNum) != 0 Then SubString(A0.TaxIdNum, CharIndex(\'-" +
            "\', A0.TaxIdNum)+1, Len(A0.TaxIdNum)) Else \'\' End \r\n+ \',\' + IsNull(A0.U_HBT_MunMe" +
            "d,\'\') + \',\' + IsNull(A0.PrintHeadr,\'\') + \',\' +  IsNull(A0.U_SEI_FEActEco,\'\') as " +
            "\'cadena\'\r\nFrom OADM A0\r\nInner Join ADM1 A1 ON A0.Code= A1.Code\r\nLeft Join \"@HBT_" +
            "MUNICIPIO\" A2 On A0.U_HBT_MunMed = A2.Code\r\nLeft Join OCRY A3 On A0.Country = A3" +
            ".Code\r\n\r\nUnion All\r\n\r\nSelect \'TAC\' + \',\' + IsNull(A3.\"U_Codigo\",\'\') + \',\' + \'\' +" +
            " \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \'," +
            "\' + \'\' + \',\' + \'\' As \'Cadena\'\r\nFrom OADM A0\r\nInner Join (SELECT Top 1 T1.\"Code\" " +
            ", \"U_Codigo\"=STUFF(\r\n\t\t\t\t(SELECT \';\' + \"U_Codigo\" AS [text()]\r\n\t\t\t\t\tFROM \"@FEDIA" +
            "N_SN_RESPO\" XT\r\n\t\t\t\t\tWhere \"Code\" = (Select \"TaxIdNum\" From \"OADM\")\r\n\t\t\t\t\tOrder " +
            "By \"U_Codigo\"\r\n\t\t\t\t\tFOR XML PATH(\'\')), 1, 1, \'\') \r\n\t\t\t\tFROM \"@FEDIAN_SN_RESPO\" T" +
            "\r\n\t\t\t\tINNER JOIN \"@FEDIAN_SN\" T1 ON T.\"Code\" = T1.\"Code\" And T1.\"Code\" = (Select" +
            " \"TaxIdNum\" From \"OADM\")\r\n\t\t\t\tGROUP BY T1.\"Code\", \"U_Codigo\") A3 On A0.\"TaxIdNum" +
            "\" = A3.\"Code\"\r\n\r\nUnion All\r\n\r\nSelect \'DFE\' + \',\' + IsNull(A0.U_HBT_MunMed,\'\') + " +
            "\',\' + IsNull(Substring(A0.U_HBT_MunMed,1,2),\'\') + \',\' + IsNull(A0.Country,\'\') + " +
            "\',\' + IsNull(A1.ZipCode,\'\') + \',\' +\r\nISNull(A3.Name,\'\') + \',\' + IsNull(A2.Name,\'" +
            "\') + \',\' + IsNull(A2.U_NomDepartamento,\'\') + \',\' + \'\' as \'cadena\'\r\nFrom OADM A0\r" +
            "\nInner Join ADM1 A1 ON A0.Code= A1.Code\r\nLeft Join \"@HBT_MUNICIPIO\" A2 On A0.U_H" +
            "BT_MunMed = A2.Code\r\nLeft Join OCRY A3 On A0.Country = A3.Code\r\n\r\nUnion All\r\n\r\nS" +
            "elect \'CDE\' + \',\' + \'1\' + \',\' + IsNull(A0.Manager,\'\') + \',\' + IsNull(A0.Phone1,\'" +
            "\') + \',\' + IsNull(A0.E_Mail,\'\')\r\n+ \',\' + \'\' + \',\' + \'\' As \'Cadena\'\r\nFrom OADM A0" +
            "\r\n\r\nUnion ALL\r\n\r\nSelect \'GTE\' + \',\' + IsNull(A2.U_Codigo,\'\') + \',\' + IsNull(A2.U" +
            "_Desc,\'\') As \'Cadena\'\r\nFrom OADM A0\r\nInner Join [@FEDIAN_SN] A1 On A0.TaxIdNum =" +
            " A1.Code\r\nInner Join [@FEDIAN_SN_TRIB] A2 On A1.Code = A2.Code\r\n\r\nUnion All\r\n\r\nS" +
            "elect \'ADQ\' + \',\' + Case When A1.U_HBT_TipEnt = \'1\' Then \'2\' When A1.U_HBT_TipEn" +
            "t = \'2\' Then \'1\' Else \'1\' End + \',\' + \r\nCase When CharIndex(\'-\', A1.LicTradNum) " +
            "= 0 Then A1.LicTradNum Else SubString(A1.LicTradNum, 1, CharIndex(\'-\', A1.LicTra" +
            "dNum)-1) End \r\n+ \',\' + IsNull(A1.U_HBT_TipDoc,\'\')  + \',\' + \'48\'  \r\n+ \',\' + \'\' + " +
            "\',\' + Case When IsNull(A1.U_HBT_TipEnt,\'\') = \'1\' Then (IsNull(A1.U_HBT_Nombres,\'" +
            "\') + \' \' + IsNull(A1.U_HBT_Apellido1,\'\') + \' \' + IsNull(A1.U_HBT_Apellido2,\'\')) " +
            "Else A1.CardName End + \',\' +\r\nCase When IsNull(A1.U_HBT_TipEnt,\'\') = \'1\' Then (I" +
            "sNull(A1.U_HBT_Nombres,\'\') + \' \' + IsNull(A1.U_HBT_Apellido1,\'\') + \' \' + IsNull(" +
            "A1.U_HBT_Apellido2,\'\')) Else A1.CardName End + \',\' + \r\nCase When IsNull(A1.U_HBT" +
            "_TipEnt,\'\') = \'1\' Then (IsNull(A1.U_HBT_Nombres,\'\') + \' \' + IsNull(A1.U_HBT_Apel" +
            "lido1,\'\') + \' \' + IsNull(A1.U_HBT_Apellido2,\'\')) Else A1.CardName End + \',\' + \'\'" +
            " + \',\' + \'\' + \',\' +\r\nIsNull(SubString(A1.U_HBT_MunMed,1,2),\'\') + \',\' + IsNull(A1" +
            ".Address,\'\') + \',\' + IsNull(A2.Name,\'\') + \',\' + IsNull(A1.ZipCode,\'\') + \',\' + Is" +
            "Null(A1.Country,\'\') + \',\' +\r\n\'\' + \',\' + \'\' + \',\' + \'\' + \',\' + IsNull(A2.U_NomDep" +
            "artamento,\'\') + \',\' + \'\' +\',\' + IsNull(A3.Name,\'\') + \',\' +\r\nCase When CharIndex(" +
            "\'-\', A1.LicTradNum) != 0 Then SubString(A1.LicTradNum, CharIndex(\'-\', A1.LicTrad" +
            "Num)+1, Len(A1.LicTradNum)) Else \'\' End + \',\' +\r\nIsNull(A1.U_HBT_MunMed,\'\') + \'," +
            "\' + \'\'  As \'Cadena\'\r\nFrom ORIN A0 \r\nInner Join OCRD A1 On A0.CardCode = A1.CardC" +
            "ode\r\nLeft Join \"@HBT_MUNICIPIO\" A2 On A1.U_HBT_MunMed = A2.Code\r\nLeft Join OCRY " +
            "A3 On A1.Country = A3.Code\r\nWhere A0.DocEntry = {0}\r\n\r\nUnion All\r\n\r\n\r\nSelect \'TC" +
            "R\' + \',\' + IsNull(A2.U_Codigo,\'\') + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + " +
            "\',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\'\r\nas \'cadena\'\r\nFr" +
            "om ORIN A0\r\nInner Join OCRD A1 ON A0.CardCode = A1.CardCode\r\nInner Join (SELECT " +
            "Top 1 T1.Code, U_Codigo=STUFF(\r\n\t\t\t\t\t(SELECT \';\' + U_Codigo AS [text()]\r\n\t\t\t\t\t\tF" +
            "ROM [@FEDIAN_SN_RESPO] XT\r\n\t\t\t\t\t\tINNER JOIN [@FEDIAN_SN] XT1 ON XT.Code = XT1.Co" +
            "de\r\n\t\t\t\t\t\t--*************CAMBIAR DOCENTRY POR VARIABLE*************\r\n\t\t\t\t\t\tWhere" +
            " XT1.Code = (Select CardCode From ORIN Where DocEntry = {0})\r\n\t\t\t\t\t\tOrder By U_C" +
            "odigo\r\n\t\t\t\t\t\tFOR XML PATH(\'\')), 1, 1, \'\') \r\n\t\t\t\t\tFROM [@FEDIAN_SN_RESPO] T\r\n\t\t\t\t" +
            "\tINNER JOIN [@FEDIAN_SN] T1 ON T.Code = T1.Code And T1.Code = (Select CardCode F" +
            "rom ORIN Where DocEntry = {0})\r\n\t\t\t\t\tGROUP BY T1.Code, U_Codigo) A2 On A1.CardCo" +
            "de = A2.Code\r\nWhere A0.DocEntry = {0}\r\n\r\nUnion All\r\n\r\nSelect \'ILA\' + \',\' + A1.Ca" +
            "rdName + \',\' + \r\nCase When CharIndex(\'-\', A1.LicTradNum) = 0 Then A1.LicTradNum " +
            "Else SubString(A1.LicTradNum, 1, CharIndex(\'-\', A1.LicTradNum)-1) End \r\n+ \',\' + " +
            "IsNull(A1.U_HBT_TipDoc,\'\') + \',\' + \r\nCase When CharIndex(\'-\', A1.LicTradNum) != " +
            "0 Then SubString(A1.LicTradNum, CharIndex(\'-\', A1.LicTradNum)+1, Len(A1.LicTradN" +
            "um)) Else \'\' End As \'Cadena\'\r\nFrom ORIN A0 \r\nInner Join OCRD A1 On A0.CardCode =" +
            " A1.CardCode\r\nWhere A0.DocEntry = {0}\r\n\r\nUnion All\r\n\r\nSelect \'DFA\' + \',\' + IsNul" +
            "l(A1.Country,\'\') + \',\' + IsNull(SubString(A1.U_HBT_MunMed,1,2),\'\') + \',\' + IsNul" +
            "l(A1.ZipCode,\'\') + \',\' + IsNull(A1.U_HBT_MunMed,\'\') + \',\' + \r\nIsNull(A2.Name,\'\')" +
            " + \',\' + IsNull(A3.Name,\'\') + \',\' + IsNull(A3.U_NomDepartamento,\'\') + \',\' + \'\' A" +
            "s \'Cadena\'\r\nFrom ORIN A0\r\nInner Join OCRD A1 On A0.CardCode = A1.CardCode\r\nLeft " +
            "Join OCRY A2 On A1.Country = A2.Code\r\nLeft Join \"@HBT_MUNICIPIO\" A3 On A1.U_HBT_" +
            "MunMed = A3.Code\r\nWhere A0.DocEntry = {0}\r\n\r\nUnion All\r\n\r\nSelect \'GTA\' + \',\' + I" +
            "sNull(A2.U_Codigo,\'\') + \',\' + IsNull(A2.U_Desc,\'\') As \'Cadena\'\r\nFrom ORIN A0\r\nIn" +
            "ner Join [@FEDIAN_SN] A1 On A0.CardCode = A1.Code\r\nInner Join [@FEDIAN_SN_TRIB] " +
            "A2 On A1.Code = A2.Code\r\nWhere A0.DocEntry = {0}\r\n\r\nUnion All\r\n\r\nSelect \'TOT\' + " +
            "\',\' + \r\nCast(Cast(Sum(A1.Linetotal) as decimal (15,6)) as Nvarchar(100)) + \',\' +" +
            " Case When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End + \',\' + \r\nCast(Cast(A0." +
            "BaseAmnt as decimal (15,6)) as Nvarchar(100)) + \',\' + Case When A0.DocCur = \'$\' " +
            "Then \'COP\' Else A0.DocCur End + \',\' + \r\nCast(Cast(A0.DocTotal as decimal (15,6))" +
            " as Nvarchar(100)) + \',\' + Case When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur E" +
            "nd + \',\' + \r\nCast(Cast(Sum(A1.Linetotal)-A0.DiscSum+A0.VatSum as decimal (14,0))" +
            " as Nvarchar(100)) + \',\' + Case When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur E" +
            "nd + \',\' + \r\nCast(Cast(A0.DiscSum as decimal (15,6)) as Nvarchar(100)) + \',\' + C" +
            "ase When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End + \',\' + \r\nCast(Cast(A0.Va" +
            "tSum as decimal (15,6)) as Nvarchar(100)) + \',\' + Case When A0.DocCur = \'$\' Then" +
            " \'COP\' Else A0.DocCur End + \',\' + \r\nCast(Cast(A0.DpmAmnt as decimal (15,6)) as N" +
            "varchar(100)) + \',\' + Case When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End + " +
            "\',\' + \'\' + \',\' + \'\' As \'Cadena\'\r\nFrom ORIN A0\r\nInner Join RIN1 A1 On A0.DocEntry" +
            " = A1.DocEntry\r\nWhere A0.DocEntry = {0}\r\nGroup By A0.DocCur, A0.BaseAmnt, A0.Doc" +
            "Total, A0.DiscSum, A0.VatSum, A0.DpmAmnt\r\n\r\nUnion All\r\n\r\nSelect \'TIM\' + \',\' + \'f" +
            "alse\' + \',\' + \r\nCast(Cast(A0.VatSum as decimal (15,6)) as Nvarchar(100))  + \',\' " +
            "+ Case When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End As \'Cadena\'\r\nFrom ORIN" +
            " A0\r\nWhere A0.DocEntry = {0} And IsNull(A0.VatSum ,0) != 0\r\n\r\nUnion All\r\n\r\nSelec" +
            "t \'IMP\' + \',\' + IsNull(A2.U_SEI_FETributo,\'\') + \',\' + \r\nCast(Cast(Sum(A1.BaseSum" +
            ") as decimal (15,6)) as Nvarchar(100)) + \',\' + \r\nCase When A0.DocCur = \'$\' Then " +
            "\'COP\' Else A0.DocCur End + \',\' +\r\nCast(Cast(Sum(A1.TaxSum) as decimal (15,6)) as" +
            " Nvarchar(100)) + \',\' +\r\nCase When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End" +
            " + \',\' + \r\nCast(Cast(A1.TaxRate as decimal (14,2)) as Nvarchar(100)) \r\n+ \',\' + \'" +
            "\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' As \'Cadena\'\r\nFrom ORIN A0\r\nInner Join RIN4 A1" +
            " On A0.DocEntry = A1.DocEntry\r\nInner Join OSTC A2 On A1.StcCode = A2.Code\r\nWhere" +
            " A0.DocEntry = {0} And IsNull(A1.TaxSum ,0) != 0\r\nGroup By A0.DocCur, A1.TaxRate" +
            ", A2.U_SEI_FETributo\r\n\r\nUnion All\r\n\r\nSelect \'DSC\' + \',\' + \'false\' + \',\' + \r\nCast" +
            "(Cast(A0.DiscPrcnt as decimal (15,2)) as Nvarchar(100)) + \',\' + Cast(Cast(A0.Dis" +
            "cSum as decimal (15,6)) as Nvarchar(100)) + \',\' + \r\nCase When A0.DocCur = \'$\' Th" +
            "en \'COP\' Else A0.DocCur End + \',\' + IsNull(A0.U_SEI_FEDescu,\'\') + \',\' + IsNull(A" +
            "2.Descr,\'\') + \',\' +\r\nCast(Cast(Sum(A3.LineTotal) as decimal (15,6)) as Nvarchar(" +
            "100)) + \',\' + Case When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End + \r\n\',\' + " +
            "\'\' + \',\' + \'1\'  As \'Cadena\'\r\nFrom ORIN A0\r\nLeft Join CUFD A1 On A1.TableID = \'OR" +
            "IN\' And A1.AliasID = \'SEI_FEDescu\'\r\nLeft Join UFD1 A2 On A2.TableID = A1.TableID" +
            " And A2.FieldID = A1.FieldID And A0.U_SEI_FEDescu = A2.FldValue\r\nLeft Join RIN1 " +
            "A3 On A0.DocEntry = A3.DocEntry\r\nWhere A0.DocEntry = {0} And IsNull(A0.DiscSum,0" +
            ") != 0\r\nGroup By A0.DiscPrcnt, A0.DiscSum, A0.DocCur, A0.U_SEI_FEDescu, A2.Descr" +
            "\r\n\r\nUnion All\r\n\r\nSelect \'DRF\' + \',\' + IsNull(A2.U_NumResol,\'\') + \',\' + IsNull(CO" +
            "NVERT(char(10), A2.U_FechaDesde,126),\'\') + \',\' + IsNull(CONVERT(char(10), A2.U_F" +
            "echaHasta,126),\'\') + \',\' + \r\nIsNull(A1.BeginStr,\'\') + \',\' + IsNull(Cast(Cast(A1." +
            "InitialNum as int) as Nvarchar(100)),\'\') + \',\' + IsNull(Cast(Cast(A1.LastNum as " +
            "int) as Nvarchar(100)),\'\')\r\nFrom ORIN A0\r\nInner Join NNM1 A1 On A0.Series = A1.S" +
            "eries\r\nInner Join \"@FEDIAN_NUMAUTORI\" A2 On A1.Series = A2.Code\r\nWhere A0.DocEnt" +
            "ry = {0} And IsNull(A1.LastNum,\'\') != \'\'\r\n\r\nUnion All\r\n\r\nSelect \r\n\'NOT,2_ La mer" +
            "cancía viaja por cuenta y riesgo del comprador. El vendedor se reserva el derech" +
            "o de dominio sobre la mercancía hasta su pago total. Con esta firma el comprador" +
            " declara haber recibido a satisfacción real y materialmente las mercancías descr" +
            "itas en este documento\' As \'Cadena\'\r\nFrom OADM A0\r\n\r\nUnion All\r\n\r\nSelect \r\n\'NOT," +
            "5_ ACTIVIDAD COMERCIAL 4659 - TARIFA 11.04 x 1000\' + \'|\' + \r\n\'IVA REGIMEN COMUN " +
            "- AUTORRETENEDOR RENTA RESOLUCION No. 008543 DE 08/13/09\' As \'Cadena\'\r\nFrom OADM" +
            " A0\r\n\r\nUnion All\r\n\r\nSelect \'NOT,6_ \' + A1.SlpName  As \'Cadena\'\r\nFrom ORIN A0\r\nIn" +
            "ner Join OSLP A1 On A0.SlpCode = A1.SlpCode\r\nWhere A0.DocEntry = {0} And A0.SlpC" +
            "ode != -1\r\n\r\nUnion All\r\n\r\nSelect \r\n\'NOT,7_ IVA RÉGIMEN COMÚN\' + \'|\' + IsNull(A1." +
            "IntrntAdrs,\'\') As \'Cadena\'\r\nFrom OADM A0\r\nInner Join ADM1 A1 ON A0.Code= A1.Code" +
            "\r\n\r\nUnion All\r\n\r\nSelect \'NOT,12_ \' + REPLACE(REPLACE(REPLACE(Cast(IsNull(A0.Comm" +
            "ents,\'\') as Nvarchar(max)),CHAR(10),\' \'),CHAR(13),\' \'), \',\', \';\') As \'Cadena\'\r\nF" +
            "rom ORIN A0\r\nInner Join OADM A1 On 1 =1 \r\nWhere A0.DocEntry = {0} And IsNull(A0." +
            "Comments,\'\') != \'\'\r\n\r\nUnion All\r\n\r\nSelect \'NOT,14_ \' + A0.LicTradNum + \'|\' + A1." +
            "TaxIdNum As \'Cadena\'\r\nFrom ORIN A0\r\nInner Join OADM A1 On 1 =1 \r\nWhere A0.DocEnt" +
            "ry = {0}\r\n\r\nUnion All\r\n\r\nSelect \'OVT\' + \',\' + \'01C\' + \',\' + Cast(Cast(Sum(A1.WTA" +
            "mnt) as decimal (14,0)) as Nvarchar(100)) + \',\' + \r\nCase When A0.DocCur = \'$\' Th" +
            "en \'COP\' Else A0.DocCur End + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' As \'Cadena\'\r\nFrom O" +
            "RIN A0\r\nInner Join RIN5 A1 ON A0.DocEntry = A1.AbsEntry \r\nInner Join OWHT A2 On " +
            "A1.WTCode = A2.WTCode\r\nWhere A2.U_HBT_TipoAutoRet = \'4\' And A2.U_HBT_TipRet != \'" +
            "0\' And IsNull(A1.WTAmnt,0) != 0 And A0.DocEntry = {0}\r\nGroup By A0.DocEntry, A0." +
            "DocCur\r\n\r\nUnion All\r\n\r\nSelect \'MEP\' + \',\' + IsNull(A0.U_SEI_FEMedPago,\'\') + \',\' " +
            "+ Case When A1.\"ExtraMonth\" + A1.\"ExtraDays\" <= 0 Then \'1\' Else \'2\' End  + \',\' +" +
            "\r\nConvert(char(10), A0.DocDueDate,126) + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + " +
            "\'\' + \',\' + \'\' + \',\' + \'\' As \'Cadena\'\r\nFrom ORIN A0\r\nInner Join OCTG A1 On A0.Gro" +
            "upNum = A1.GroupNum\r\nWhere A0.DocEntry = {0} And IsNull(A0.U_SEI_FEMedPago,\'\') !" +
            "= \'\'\r\n\r\nUnion All\r\n\r\nSelect \'CTS\' + \',\' + \'BIOT01\' + \',\' + \'\' + \',\' + \'\' + \',\' +" +
            " \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\'\r\nFrom OADM\r\n\r\nUnion All\r\n\r\nSelec" +
            "t \'CDN\' + \',\' + A0.U_SEI_FEConcepNC + \',\' + A2.Descr + \',\' + \'\'\r\nFrom ORIN A0\r\nI" +
            "nner Join CUFD A1 On A1.TableID = \'ORIN\' And A1.AliasID = \'SEI_FEConcepNC\'\r\nInne" +
            "r Join UFD1 A2 On A2.TableID = A1.TableID And A2.FieldID = A1.FieldID And A0.U_S" +
            "EI_FEConcepNC = A2.FldValue\r\nWhere A0.DocEntry = {0}\r\n\r\nUnion All\r\n\r\nSelect \'DCN" +
            "\' + \',\' + A2.Descr \r\nFrom ORIN A0\r\nInner Join CUFD A1 On A1.TableID = \'ORIN\' And" +
            " A1.AliasID = \'SEI_FEConcepNC\'\r\nInner Join UFD1 A2 On A2.TableID = A1.TableID An" +
            "d A2.FieldID = A1.FieldID And A0.U_SEI_FEConcepNC = A2.FldValue\r\nWhere A0.DocEnt" +
            "ry = {0}\r\n\r\n)T0\r\n\r\nUnion All\r\n\r\nSelect A1.LineNum, 2 as \'ordenplano\', \'ITE\' + \'," +
            "\' + Cast(A1.VisOrder+1 as Nvarchar(100)) + \',\' + \'\' + \',\' +\r\nCase When A1.Quanti" +
            "ty = 0 Then Cast(Cast(1 as decimal (14,0)) as Nvarchar(100)) \r\nElse Cast(Cast(A1" +
            ".Quantity as decimal (14,4)) as Nvarchar(100)) End + \',\' + \r\nCASE \r\nWHEN IsNull(" +
            "A1.\"UomCode\",\'\') = \'Manual\' Then IsNull((Select IsNull(P0.\"U_DIAN_UM\",\'\') From \"" +
            "@FEDIAN_HOMOL_UM\" P0 Where P0.\"U_SAP_UM\" = A1.\"unitMsr\"),\'\') \r\nElse IsNull((Sele" +
            "ct IsNull(P0.\"U_DIAN_UM\",\'\') From \"@FEDIAN_HOMOL_UM\" P0 Where P0.\"U_SAP_UM\" = A1" +
            ".\"UomCode\"),\'\') End + \',\' + \r\nCast(Cast(A1.LineTotal as decimal (15,6)) as Nvarc" +
            "har(100)) + \',\' + Case When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End + \',\' " +
            "+\r\nCase When A1.Quantity = 0 Then Cast(Cast(A1.LineTotal/1 as decimal (15,6)) as" +
            " Nvarchar(100)) \r\nElse Cast(Cast(A1.LineTotal/A1.Quantity as decimal (15,6)) as " +
            "Nvarchar(100)) End + \',\' + Case When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur E" +
            "nd + \',\' + \r\n\'\' + \',\' + \'\' + \',\' + Replace(A1.Dscription,\',\',\'.\') + \',\' + \'\' + \'" +
            ",\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \r\n\'\' + \',\' + Case When A0.Docty" +
            "pe = \'S\' Then A1.AcctCode Else Replace(A1.ItemCode,\',\',\'.\') End + \',\' + \r\nCast(C" +
            "ast(A1.LineTotal as decimal (15,6)) as Nvarchar(100)) + \',\' + Case When A0.DocCu" +
            "r = \'$\' Then \'COP\' Else A0.DocCur End + \',\' + \r\nCast(Cast(A1.LineTotal as decima" +
            "l (15,6)) as Nvarchar(100)) + \',\' + Case When A0.DocCur = \'$\' Then \'COP\' Else A0" +
            ".DocCur End + \',\' + \r\nCast(Cast(A1.LineTotal as decimal (15,6)) as Nvarchar(100)" +
            ") + \',\' + Case When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End + \',\' + \r\n\'\' +" +
            " \',\' + \'\' + \',\' + \r\nCase When A1.Quantity = 0 Then Cast(Cast(1 as decimal (14,0)" +
            ") as Nvarchar(100)) \r\nElse Cast(Cast(A1.Quantity as decimal (14,4)) as Nvarchar(" +
            "100)) End + \',\' + CASE \r\nWHEN IsNull(A1.\"UomCode\",\'\') = \'Manual\' Then IsNull((Se" +
            "lect IsNull(P0.\"U_DIAN_UM\",\'\') From \"@FEDIAN_HOMOL_UM\" P0 Where P0.\"U_SAP_UM\" = " +
            "A1.\"unitMsr\"),\'\') \r\nElse IsNull((Select IsNull(P0.\"U_DIAN_UM\",\'\') From \"@FEDIAN_" +
            "HOMOL_UM\" P0 Where P0.\"U_SAP_UM\" = A1.\"UomCode\"),\'\') End + \',\' + \r\nCast(Cast(A1." +
            "LineTotal as decimal (15,6)) as Nvarchar(100)) + \',\' + Case When A0.DocCur = \'$\'" +
            " Then \'COP\' Else A0.DocCur End + \',\' +\r\nCast(A0.SlpCode as Nvarchar(100)) as \'Ca" +
            "dena\'\r\nFrom ORIN A0 \r\nInner Join RIN1 A1 On A0.DocEntry = A1.DocEntry\r\nWhere A0." +
            "DocEntry = {0}\r\n\r\nUnion All\r\n\r\nSelect A1.LineNum, 3 as \'ordenplano\', \'IAE\' + \',\'" +
            " + Cast(IsNull(A1.ItemCode,\'\') as Nvarchar(100)) + \',\' + \r\nIsNull(A2.U_SEI_FEIde" +
            "nt,\'\') + \',\' + \'\' + \',\' + \'\' as \'cadena\'\r\nFrom ORIN A0 \r\nInner Join RIN1 A1 On A" +
            "0.DocEntry = A1.DocEntry\r\nInner Join OITM A2 On A1.ItemCode = A2.ItemCode\r\nWhere" +
            " A0.DocEntry = {0}\r\n\r\nUnion All\r\n\r\nSelect A1.LineNum, 3 as \'ordenplano\', \'TII\' +" +
            " \',\' + Cast(Cast(A2.TaxSum as decimal (14,0)) as Nvarchar(100)) + \',\' + \r\nCase W" +
            "hen A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End + \',\' + \'false\'\r\nFrom ORIN A0 " +
            "\r\nInner Join RIN1 A1 On A0.DocEntry = A1.DocEntry\r\nInner Join RIN4 A2 On A1.DocE" +
            "ntry = A2.DocEntry And A1.LineNum = A2.LineNum\r\nWhere A0.DocEntry = {0} And A2.E" +
            "xpnsCode = -1\r\nGroup By A0.DocEntry, A0.DocCur, A2.TaxSum, A1.LineNum\r\n\r\nUnion A" +
            "ll\r\n\r\nSelect A1.LineNum, 4 as \'ordenplano\', \'IIM\' + \',\' + IsNull(A3.U_SEI_FETrib" +
            "uto,\'\') + \',\' + Cast(Cast(A2.TaxSum as decimal (14,0)) as Nvarchar(100)) + \',\' +" +
            " \r\nCase When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End + \',\' + Cast(Cast(A2." +
            "BaseSum as decimal (14,0)) as Nvarchar(100)) + \r\n\',\' + Case When A0.DocCur = \'$\'" +
            " Then \'COP\' Else A0.DocCur End + \',\' + Cast(Cast(A2.TaxRate as decimal (14,2)) a" +
            "s Nvarchar(100))\r\n+ \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' as \'Cadena\'\r\nFrom " +
            "ORIN A0 \r\nInner Join RIN1 A1 On A0.DocEntry = A1.DocEntry\r\nInner Join RIN4 A2 On" +
            " A1.DocEntry = A2.DocEntry And A1.LineNum = A2.LineNum\r\nInner Join OSTC A3 On A2" +
            ".StcCode = A3.Code\r\nWhere A0.DocEntry = {0} And A2.ExpnsCode = -1\r\nGroup By A0.D" +
            "ocEntry, A0.DocCur, A2.BaseSum, A2.TaxRate, A2.TaxSum, A1.LineNum, A3.U_SEI_FETr" +
            "ibuto\r\n)C0 Order by LineNum, ordenplano;")]
        public string NotaCredito {
            get {
                return ((string)(this["NotaCredito"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select \r\n\'FAC\' as \"TipoDocumento\", \'92063fe528f34ab4add59a441822e7e1\' as \"GuidEmp" +
            "resa\", \'3b3cca1a9b124bffb82e0003dafb1616\' as \"GuidOrigen\", \r\n\'77e7c1be44b8e03408" +
            "15fe688270bcf28cac68dbd15e334f6a830f22cf09bbff\' as \"HashSeguridad\", IsNull(A2.\"U" +
            "_ClaveTec\",\'\') as \"ClaveTecnica\",\r\nA0.\"DocEntry\" as \"CodigoErp\", IsNull(A1.\"Begi" +
            "nStr\",\'\') + Cast(A0.\"DocNum\" as nVarchar(100)) as \"NumeroDocumento\",\r\n\r\nCase Whe" +
            "n A3.\"U_HBT_TipEnt\" = \'2\' Then \'1\' When A3.\"U_HBT_TipEnt\" = \'1\' Then \'2\' End \"Em" +
            "iTipoPersona\", A3.\"U_SEI_FETipDoc\" as \"EmiTipoIdentificacion\",\r\nCase When CharIn" +
            "dex(\'-\', A3.\"TaxIdNum\") = 0 Then A3.\"TaxIdNum\" Else SubString(A3.\"TaxIdNum\", 1, " +
            "CharIndex(\'-\', A3.\"TaxIdNum\")-1) End \"EmiIdentificacion\",\r\nCase When CharIndex(\'" +
            "-\', A3.\"TaxIdNum\") != 0 Then SubString(A3.\"TaxIdNum\", CharIndex(\'-\', A3.\"TaxIdNu" +
            "m\")+1, Len(A3.\"TaxIdNum\")) Else \'\' End \"EmiDVIdentificacion\",\r\n\r\nCase When A4.\"U" +
            "_HBT_TipEnt\" = \'2\' Then \'1\' When A4.\"U_HBT_TipEnt\" = \'1\' Then \'2\' End \"Comprador" +
            "TipoPersona\", A4.\"U_HBT_TipDoc\" as \"CompradorTipoIdentificacion\", \r\nCase When Ch" +
            "arIndex(\'-\', A4.\"LicTradNum\") = 0 Then A4.\"LicTradNum\" Else SubString(A4.\"LicTra" +
            "dNum\", 1, CharIndex(\'-\', A4.\"LicTradNum\")-1) End \"CompradorIdentificacion\",\r\nCas" +
            "e When CharIndex(\'-\', A4.\"LicTradNum\") != 0 Then SubString(A4.\"LicTradNum\", Char" +
            "Index(\'-\', A4.\"LicTradNum\")+1, Len(A4.\"LicTradNum\")) Else \'\' End \"CompradorDVIde" +
            "ntificacion\",\r\nA4.\"U_SEI_FERegFis\" as \"CompradorTipoRegimen\", \'ZZ\' as \"Comprador" +
            "RespFiscal\", \'ZZ\' as \"CompradorImpuesto\", A4.\"CardName\" as \"CompradorRazonSocial" +
            "\",\r\nA4.\"U_HBT_Nombres\" as \"CompradorPrimerNombre\", \'\' as \"CompradorSegundoNombre" +
            "\", IsNull(A4.\"U_HBT_Apellido1\",\'\') + \' \' + IsNull(A4.\"U_HBT_Apellido2\",\'\') as \"C" +
            "ompradorApellidos\",\r\nA4.\"CardName\" as \"CompradorNombreCompleto\", A4.\"Country\" as" +
            " \"CompradorPais\", A5.\"Name\" as \"CompradorNombrePais\", A6.\"U_NomDepartamento\" as " +
            "\"CompradorDepartamento\",\r\nA6.\"Code\" as \"CompradorCodDepartamento\", A6.\"U_NomDepa" +
            "rtamento\" as \"CompradorCiudad\", A6.\"Code\" as \"CompradorCodCiudad\", IsNull(A4.\"Zi" +
            "pCode\",\'\') as \"CompradorCodPostal\",\r\nA4.\"Address\" as \"CompradorDireccion\", \'True" +
            "\' as \"CompradorEnviarCorreo\", IsNull(A4.\"Phone1\",\'\') as \"CompradorTelefonoCont\"," +
            " IsNull(A4.\"E_Mail\",\'\') as \"CompradorCorreoElectronico\",\r\n\r\nA2.\"U_DocDIAN\" as \"F" +
            "acTipoFactura\", IsNull(A0.\"U_SEI_FETipOper\",\'\') as \"FacCodOperacion\", \r\nCONVERT(" +
            "char(10), A0.\"DocDate\",126) + \' \' + \r\nCASE WHEN Len (Cast(A0.\"CreateTS\" as nVarc" +
            "har(6))) = 6 THEN  SUBSTRING(Cast(A0.\"CreateTS\" as nVarchar(6)), 0,2) WHEN Len (" +
            "Cast(A0.\"CreateTS\" as nVarchar(6))) = 5 THEN  SUBSTRING ( Cast(A0.\"CreateTS\" as " +
            "nVarchar(6)), 0,1)\r\nEND +\':\'+\r\nCASE WHEN Len (Cast(A0.\"CreateTS\" as nVarchar(6))" +
            ") = 6 THEN  SUBSTRING ( Cast(A0.\"CreateTS\" as nVarchar(6)), 3,2) WHEN Len (Cast(" +
            "A0.\"CreateTS\" as nVarchar(6))) = 5 THEN  SUBSTRING ( Cast(A0.\"CreateTS\" as nVarc" +
            "har(6)), 2,2)\r\nEND +\':\'+\r\nCASE WHEN Len (Cast(A0.\"CreateTS\" as nVarchar(6))) = 6" +
            " THEN  SUBSTRING ( Cast(A0.\"CreateTS\" as nVarchar(6)), 5,2) WHEN Len (Cast(A0.\"C" +
            "reateTS\" as nVarchar(6))) = 5 THEN  SUBSTRING ( Cast(A0.\"CreateTS\" as nVarchar(6" +
            ")), 4,2)  \r\nEND \"FacFechaHoraFactura\",\r\n\r\nA7.\"ISOCurrCod\" as \"FacCodMoneda\", A8." +
            "\"TotalImporteBruto\" as \"FacTotalImporteBruto\", \'0\' as \"FacTotalCargos\", A0.\"Disc" +
            "Sum\" as \"FacTotalDescuentos\", \r\nA9.\"BaseImpu\" as \"FacTotalBaseImponible\", A8.\"To" +
            "talImporteBruto\" + A0.\"VatSum\"  as \"FacTotalBrutoMasImp\", \'0\' as \"FacTotalAntici" +
            "pos\", A0.\"DocTotal\" as \"FacTotalFactura\",\r\n\r\nCase When A10.\"ExtraMonth\" + A10.\"E" +
            "xtraDays\" <= 0 Then \'1\' Else \'2\' End \"FacMetodoPago\", A0.\"U_SEI_FEMedPago\" as \"F" +
            "acFormaPago\", \r\nCONVERT(char(10), A0.\"DocDueDate\",126) as \"FacVencimientoFac\",\r\n" +
            "\r\nA11.\"VisOrder\"+1 as \"DetFacConsecutivo\", A11.\"ItemCode\" as \"Codigo\", A11.\"Item" +
            "Code\" as \"CodigoEstandar\", A14.\"U_SEI_FEIdent\" as \"Codificacion\",\r\nA11.\"Dscripti" +
            "on\" as \"Descripcion\", IsNull(A11.\"Quantity\",\'0\') as \"Cantidad\",\r\nCASE \r\nWHEN IsN" +
            "ull(A11.\"UomCode\",\'\') = \'Manual\' Then IsNull((Select IsNull(P0.\"U_DIAN_UM\",\'\') F" +
            "rom \"@FEDIAN_HOMOL_UM\" P0 Where P0.\"U_SAP_UM\" = A11.\"unitMsr\"),\'\') \r\nElse IsNull" +
            "((Select IsNull(P0.\"U_DIAN_UM\",\'\') From \"@FEDIAN_HOMOL_UM\" P0 Where P0.\"U_SAP_UM" +
            "\" = A11.\"UomCode\"),\'\') End \"UnidadMedida\",\r\nA11.\"Price\" as \"PrecioUnitario\", A11" +
            ".\"Price\" as \"PrecioSinImpuestos\", A11.\"LineTotal\"+A11.\"VatSum\" as \"PrecioTotal\"," +
            "\r\n\r\nA11.\"VisOrder\"+1 as \"Secuencia\", A13.\"U_SEI_FETributo\" as \"CodigoImpuesto\", " +
            "A13.\"Name\" as \"NombreImpuesto\", \'False\' as \"EsRetencionImpuesto\",\r\nA12.\"BaseSum\"" +
            " as \"BaseImponible\", Cast(A12.\"TaxRate\" as decimal(19,2)) as \"Porcentaje\", A12.\"" +
            "TaxSum\" as \"ValorImpuesto\",\r\n\r\nCONVERT(char(10), A2.\"U_FechaDesde\",126) as \"AutF" +
            "echaInicio\", CONVERT(char(10), A2.\"U_FechaHasta\",126) as \"AutFechaFinal\", \r\nA2.\"" +
            "U_NumResol\" as \"AutNumAutorizacion\", A1.\"BeginStr\" as \"AutPrefijo\", A2.\"U_Initia" +
            "lNum\" as \"AutSecuenciaInicio\", A2.\"U_LastNum\" as \"AutSecuenciaFinal\"\r\nFrom OINV " +
            "A0\r\nInner Join NNM1 A1 On A0.\"Series\" = A1.\"Series\"\r\nInner Join \"@FEDIAN_NUMAUTO" +
            "RI\" A2 On A1.\"Series\" = A2.\"Code\"\r\nInner Join OADM A3 On 1 = 1\r\nInner Join OCRD " +
            "A4 On A0.\"CardCode\" = A4.\"CardCode\"\r\nInner Join OCRY A5 On A4.\"Country\" = A5.\"Co" +
            "de\"\r\nInner Join \"@HBT_MUNICIPIO\" A6 On A4.\"U_HBT_MunMed\" = A6.\"Code\"\r\nInner Join" +
            " OCRN A7 On A0.\"DocCur\" = A7.\"CurrCode\"\r\nInner Join (Select \"DocEntry\", Sum(\"Lin" +
            "eTotal\") as \"TotalImporteBruto\" From INV1 Group By \"DocEntry\") A8 On A0.\"DocEntr" +
            "y\" = A8.\"DocEntry\"\r\nInner Join (Select \"DocEntry\", Sum(\"BaseSum\") as \"BaseImpu\" " +
            "From INV4 Where \"RelateType\" = \'1\' Group By \"DocEntry\") A9 On A0.\"DocEntry\" = A9" +
            ".\"DocEntry\"\r\nInner Join OCTG A10 On A0.\"GroupNum\" = A10.\"GroupNum\"\r\nInner Join I" +
            "NV1 A11 On A0.\"DocEntry\" = A11.\"DocEntry\"\r\nInner Join INV4 A12 On A11.\"DocEntry\"" +
            " = A12.\"DocEntry\" And A11.\"LineNum\" = A12.\"LineNum\"\r\nInner Join OSTC A13 On A12." +
            "\"StcCode\" = A13.\"Code\"\r\nInner Join OITM A14 On A11.\"ItemCode\" = A14.\"ItemCode\"\r\n" +
            "Where A0.\"DocEntry\" = {0}")]
        public string FacturaVenta {
            get {
                return ((string)(this["FacturaVenta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Select 
A0.""Code"", A0.""U_ObjType"" as ""Tipo Objeto"", A0.""U_DocType"" as ""Tipo Documento"", A1.""Name"" as ""Documento DIAN"", A0.""U_Folio"" as ""Numero Documento"", A0.""U_Prefijo"" as ""Prefijo"", A0.""U_DocNum"" as ""Numero Interno"", 
A0.""U_Status"" as ""Codigo Estado"", A0.""U_Resultado"" as ""Descripcion Estado"", A0.""U_ProcessID"" as ""ID Proceso"", 
A0.""U_Fecha_Envio"" as ""Fecha de contabilizacion"", A0.""U_Hora_Envio"" as ""Hora de creacion"", A0.""U_Usuario_Envio"" as ""Usuario Envio"", 
A0.""U_Det_Peticion"" as ""Detalle Peticion"", A0.""U_Respuesta_Int"" as ""Respuesta Integracion"", A0.""U_Archivo_PDF"" as ""Archivo PDF"", A0.""U_Enlace_XML"" as ""Archivo XML"",
A0.""U_ID_Seguimiento"" as ""FebosID""
From ""@FEDIAN_MONITORLOG"" A0
Left Join ""@FEDIAN_CODDOC"" A1 On A0.""U_DocType"" = A1.""Code""
Where (A0.""U_Fecha_Envio"" Between '{0}' and '{1}' or IsNull(A0.""U_Fecha_Envio"",'') = '') and (A0.""U_DocType"" = '{2}' OR IsNull('{2}','')='') and (A0.""U_Status"" = '{3}' OR IsNull('{3}','')='')
Order By Cast(A0.""Code"" as int)")]
        public string CargueMonitor {
            get {
                return ((string)(this["CargueMonitor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select * from \"@FEDIAN_PARAMG\"")]
        public string PARAMG {
            get {
                return ((string)(this["PARAMG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select \"Code\" From \"@FEDIAN_MONITORLOG\" Where \"U_DocNum\" = {0}")]
        public string GetCodeLog {
            get {
                return ((string)(this["GetCodeLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Select ""Code"", ""U_ProcessID"" as ""ProcessID"", ""U_ID_Seguimiento"" as ""ID_Seguimiento"", ""U_Det_Peticion"" as ""Det_Peticion""
From ""@FEDIAN_MONITORLOG""
Where (IsNull(""U_Status"",'') in ({0})) Or (IsNull(""U_Status"",'') = '' And IsNull(Cast(""U_Archivo_PDF"" as Nvarchar(2500)), '') = '' )")]
        public string ProcessStatus {
            get {
                return ((string)(this["ProcessStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FacturaExpo {
            get {
                return ((string)(this["FacturaExpo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FacturaConti {
            get {
                return ((string)(this["FacturaConti"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Select Cadena from (\r\nSelect 0 \'LineNum\', 1 as \'ordenplano\', Cadena from (\r\n\r\nSel" +
            "ect \'ENC\' + \',\' + \'ND\' + \',\' + \r\nCase When CharIndex(\'-\', A2.TaxIdNum) = 0 Then " +
            "A2.TaxIdNum Else SubString(A2.TaxIdNum, 1, CharIndex(\'-\', A2.TaxIdNum)-1) End + " +
            "\',\' + \r\nCase when CharIndex(\'-\', A1.LicTradNum) = 0 Then A1.LicTradNum Else SubS" +
            "tring(A1.LicTradNum, 1, CharIndex(\'-\', A1.LicTradNum)-1) End \r\n+ \',\' + \'UBL 2.1\'" +
            " + \',\' + \'DIAN 2.1\' + \',\' + IsNull(A4.BeginStr,\'\') + Cast(A0.DocNum as Nvarchar(" +
            "100)) + \',\' \r\n+ Convert(char(10), A0.DocDate,126) + \',\' + Convert(varchar(10), G" +
            "etDate(), 108)+ \'-05:00\' + \',\' + IsNull(A6.U_DocDIAN,\'\') + \',\'  +\r\nCase When A0." +
            "DocCur = \'$\' Then \'COP\' Else A0.DocCur End + \',\' + \'\' + \',\' + \'\' + \',\' +\r\n\'\' + \'" +
            ",\' + \'\' + \',\' + Cast(A5.NLineas as Nvarchar(5)) + \',\' + Convert(char(10), A0.Doc" +
            "DueDate,126) + \',\' + \r\n\'\' + \',\' + \'\' + \',\' + \'\' + \',\' + Substring(IsNull(A3.U_Am" +
            "biente,\'2\'),2,2) + \',\' + IsNull(A0.U_SEI_FETipOper,\'\') + \',\' + \'\' As \'Cadena\'\r\nF" +
            "rom OINV A0 \r\nInner Join OCRD A1 On A0.CardCode = A1.CardCode \r\nInner Join OADM " +
            "A2 on 1 = 1\r\nLeft Join [@FEDIAN_PARAMG] A3 On 1 = 1\r\nLeft Join NNM1 A4 On A0.Ser" +
            "ies = A4.Series\r\nLeft Join (Select DocEntry, Count(*) \'NLineas\' From INV1 Group " +
            "By DocEntry) A5 On A0.DocEntry = A5.DocEntry\r\nLeft Join \"@FEDIAN_NUMAUTORI\" A6 O" +
            "n A0.Series = A6.Code\r\nWhere A0.DocEntry = {0}\r\n\r\nUnion All \r\n\r\nSelect \'EMI\' + \'" +
            ",\' + \r\nCase When IsNull(A0.U_HBT_TipEnt,\'\') = \'1\' Then \'2\' Else \'1\' End + \',\' + " +
            "\r\nCase When CharIndex(\'-\', A0.TaxIdNum) = 0 Then A0.TaxIdNum Else SubString(A0.T" +
            "axIdNum, 1, CharIndex(\'-\', A0.TaxIdNum)-1) End + \',\' +\r\nIsNull(U_SEI_FETipDoc,\'\'" +
            ") + \',\' + \'48\' + \',\' + \'\' + \',\' + IsNull(A0.PrintHeadr,\'\') + \',\' + \r\nIsNull(A0.P" +
            "rintHeadr,\'\') + \',\' + \'\' + \',\' + \'\' + \',\' + IsNull(A1.Street,\'\') + \',\' + IsNull(" +
            "Substring(A0.U_HBT_MunMed,1,2),\'\') \r\n+ \',\' + \'\' + \',\' + IsNull(A2.Name,\'\') + \',\'" +
            " + \'\' + \',\' +\r\nIsNull(A1.Country,\'\') + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + Is" +
            "Null(A2.U_NomDepartamento,\'\') + \',\' + \'\' + \',\' + IsNull(A3.Name,\'\') + \',\' +\r\nCas" +
            "e When CharIndex(\'-\', A0.TaxIdNum) != 0 Then SubString(A0.TaxIdNum, CharIndex(\'-" +
            "\', A0.TaxIdNum)+1, Len(A0.TaxIdNum)) Else \'\' End \r\n+ \',\' + IsNull(A0.U_HBT_MunMe" +
            "d,\'\') + \',\' + IsNull(A0.PrintHeadr,\'\') + \',\' +  IsNull(A0.U_SEI_FEActEco,\'\') as " +
            "\'cadena\'\r\nFrom OADM A0\r\nInner Join ADM1 A1 ON A0.Code= A1.Code\r\nLeft Join \"@HBT_" +
            "MUNICIPIO\" A2 On A0.U_HBT_MunMed = A2.Code\r\nLeft Join OCRY A3 On A0.Country = A3" +
            ".Code\r\n\r\nUnion All\r\n\r\nSelect \'TAC\' + \',\' + IsNull(A3.\"U_Codigo\",\'\') + \',\' + \'\' +" +
            " \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \'," +
            "\' + \'\' + \',\' + \'\' As \'Cadena\'\r\nFrom OADM A0\r\nInner Join (SELECT Top 1 T1.\"Code\" " +
            ", \"U_Codigo\"=STUFF(\r\n\t\t\t\t(SELECT \';\' + \"U_Codigo\" AS [text()]\r\n\t\t\t\t\tFROM \"@FEDIA" +
            "N_SN_RESPO\" XT\r\n\t\t\t\t\tWhere \"Code\" = (Select \"TaxIdNum\" From \"OADM\")\r\n\t\t\t\t\tOrder " +
            "By \"U_Codigo\"\r\n\t\t\t\t\tFOR XML PATH(\'\')), 1, 1, \'\') \r\n\t\t\t\tFROM \"@FEDIAN_SN_RESPO\" T" +
            "\r\n\t\t\t\tINNER JOIN \"@FEDIAN_SN\" T1 ON T.\"Code\" = T1.\"Code\" And T1.\"Code\" = (Select" +
            " \"TaxIdNum\" From \"OADM\")\r\n\t\t\t\tGROUP BY T1.\"Code\", \"U_Codigo\") A3 On A0.\"TaxIdNum" +
            "\" = A3.\"Code\"\r\n\r\nUnion All\r\n\r\nSelect \'DFE\' + \',\' + IsNull(A0.U_HBT_MunMed,\'\') + " +
            "\',\' + IsNull(Substring(A0.U_HBT_MunMed,1,2),\'\') + \',\' + IsNull(A0.Country,\'\') + " +
            "\',\' + IsNull(A1.ZipCode,\'\') + \',\' +\r\nISNull(A3.Name,\'\') + \',\' + IsNull(A2.Name,\'" +
            "\') + \',\' + IsNull(A2.U_NomDepartamento,\'\') + \',\' + \'\' as \'cadena\'\r\nFrom OADM A0\r" +
            "\nInner Join ADM1 A1 ON A0.Code= A1.Code\r\nLeft Join \"@HBT_MUNICIPIO\" A2 On A0.U_H" +
            "BT_MunMed = A2.Code\r\nLeft Join OCRY A3 On A0.Country = A3.Code\r\n\r\nUnion All\r\n\r\nS" +
            "elect \'CDE\' + \',\' + \'1\' + \',\' + IsNull(A0.Manager,\'\') + \',\' + IsNull(A0.Phone1,\'" +
            "\') + \',\' + IsNull(A0.E_Mail,\'\')\r\n+ \',\' + \'\' + \',\' + \'\' As \'Cadena\'\r\nFrom OADM A0" +
            "\r\n\r\nUnion ALL\r\n\r\nSelect \'GTE\' + \',\' + IsNull(A2.U_Codigo,\'\') + \',\' + IsNull(A2.U" +
            "_Desc,\'\') As \'Cadena\'\r\nFrom OADM A0\r\nInner Join [@FEDIAN_SN] A1 On A0.TaxIdNum =" +
            " A1.Code\r\nInner Join [@FEDIAN_SN_TRIB] A2 On A1.Code = A2.Code\r\n\r\nUnion All\r\n\r\nS" +
            "elect \'ADQ\' + \',\' + Case When A1.U_HBT_TipEnt = \'1\' Then \'2\' When A1.U_HBT_TipEn" +
            "t = \'2\' Then \'1\' Else \'1\' End + \',\' + \r\nCase When CharIndex(\'-\', A1.LicTradNum) " +
            "= 0 Then A1.LicTradNum Else SubString(A1.LicTradNum, 1, CharIndex(\'-\', A1.LicTra" +
            "dNum)-1) End \r\n+ \',\' + IsNull(A1.U_HBT_TipDoc,\'\')  + \',\' + \'48\'  \r\n+ \',\' + \'\' + " +
            "\',\' + Case When IsNull(A1.U_HBT_TipEnt,\'\') = \'1\' Then (IsNull(A1.U_HBT_Nombres,\'" +
            "\') + \' \' + IsNull(A1.U_HBT_Apellido1,\'\') + \' \' + IsNull(A1.U_HBT_Apellido2,\'\')) " +
            "Else A1.CardName End + \',\' +\r\nCase When IsNull(A1.U_HBT_TipEnt,\'\') = \'1\' Then (I" +
            "sNull(A1.U_HBT_Nombres,\'\') + \' \' + IsNull(A1.U_HBT_Apellido1,\'\') + \' \' + IsNull(" +
            "A1.U_HBT_Apellido2,\'\')) Else A1.CardName End + \',\' + \r\nCase When IsNull(A1.U_HBT" +
            "_TipEnt,\'\') = \'1\' Then (IsNull(A1.U_HBT_Nombres,\'\') + \' \' + IsNull(A1.U_HBT_Apel" +
            "lido1,\'\') + \' \' + IsNull(A1.U_HBT_Apellido2,\'\')) Else A1.CardName End + \',\' + \'\'" +
            " + \',\' + \'\' + \',\' +\r\nIsNull(SubString(A1.U_HBT_MunMed,1,2),\'\') + \',\' + IsNull(A1" +
            ".Address,\'\') + \',\' + IsNull(A2.Name,\'\') + \',\' + IsNull(A1.ZipCode,\'\') + \',\' + Is" +
            "Null(A1.Country,\'\') + \',\' +\r\n\'\' + \',\' + \'\' + \',\' + \'\' + \',\' + IsNull(A2.U_NomDep" +
            "artamento,\'\') + \',\' + \'\' +\',\' + IsNull(A3.Name,\'\') + \',\' +\r\nCase When CharIndex(" +
            "\'-\', A1.LicTradNum) != 0 Then SubString(A1.LicTradNum, CharIndex(\'-\', A1.LicTrad" +
            "Num)+1, Len(A1.LicTradNum)) Else \'\' End + \',\' +\r\nIsNull(A1.U_HBT_MunMed,\'\') + \'," +
            "\' + \'\'  As \'Cadena\'\r\nFrom OINV A0 \r\nInner Join OCRD A1 On A0.CardCode = A1.CardC" +
            "ode\r\nLeft Join \"@HBT_MUNICIPIO\" A2 On A1.U_HBT_MunMed = A2.Code\r\nLeft Join OCRY " +
            "A3 On A1.Country = A3.Code\r\nWhere A0.DocEntry = {0}\r\n\r\nUnion All\r\n\r\n\r\nSelect \'TC" +
            "R\' + \',\' + IsNull(A2.U_Codigo,\'\') + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + " +
            "\',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\'\r\nas \'cadena\'\r\nFr" +
            "om OINV A0\r\nInner Join OCRD A1 ON A0.CardCode = A1.CardCode\r\nInner Join (SELECT " +
            "Top 1 T1.Code, U_Codigo=STUFF(\r\n\t\t\t\t\t(SELECT \';\' + U_Codigo AS [text()]\r\n\t\t\t\t\t\tF" +
            "ROM [@FEDIAN_SN_RESPO] XT\r\n\t\t\t\t\t\tINNER JOIN [@FEDIAN_SN] XT1 ON XT.Code = XT1.Co" +
            "de\r\n\t\t\t\t\t\t--*************CAMBIAR DOCENTRY POR VARIABLE*************\r\n\t\t\t\t\t\tWhere" +
            " XT1.Code = (Select CardCode From OINV Where DocEntry = {0})\r\n\t\t\t\t\t\tOrder By U_C" +
            "odigo\r\n\t\t\t\t\t\tFOR XML PATH(\'\')), 1, 1, \'\') \r\n\t\t\t\t\tFROM [@FEDIAN_SN_RESPO] T\r\n\t\t\t\t" +
            "\tINNER JOIN [@FEDIAN_SN] T1 ON T.Code = T1.Code And T1.Code = (Select CardCode F" +
            "rom OINV Where DocEntry = {0})\r\n\t\t\t\t\tGROUP BY T1.Code, U_Codigo) A2 On A1.CardCo" +
            "de = A2.Code\r\nWhere A0.DocEntry = {0}\r\n\r\nUnion All\r\n\r\nSelect \'ILA\' + \',\' + A1.Ca" +
            "rdName + \',\' + \r\nCase When CharIndex(\'-\', A1.LicTradNum) = 0 Then A1.LicTradNum " +
            "Else SubString(A1.LicTradNum, 1, CharIndex(\'-\', A1.LicTradNum)-1) End \r\n+ \',\' + " +
            "IsNull(A1.U_HBT_TipDoc,\'\') + \',\' + \r\nCase When CharIndex(\'-\', A1.LicTradNum) != " +
            "0 Then SubString(A1.LicTradNum, CharIndex(\'-\', A1.LicTradNum)+1, Len(A1.LicTradN" +
            "um)) Else \'\' End As \'Cadena\'\r\nFrom OINV A0 \r\nInner Join OCRD A1 On A0.CardCode =" +
            " A1.CardCode\r\nWhere A0.DocEntry = {0}\r\n\r\nUnion All\r\n\r\nSelect \'DFA\' + \',\' + IsNul" +
            "l(A1.Country,\'\') + \',\' + IsNull(SubString(A1.U_HBT_MunMed,1,2),\'\') + \',\' + IsNul" +
            "l(A1.ZipCode,\'\') + \',\' + IsNull(A1.U_HBT_MunMed,\'\') + \',\' + \r\nIsNull(A2.Name,\'\')" +
            " + \',\' + IsNull(A3.Name,\'\') + \',\' + IsNull(A3.U_NomDepartamento,\'\') + \',\' + \'\' A" +
            "s \'Cadena\'\r\nFrom OINV A0\r\nInner Join OCRD A1 On A0.CardCode = A1.CardCode\r\nLeft " +
            "Join OCRY A2 On A1.Country = A2.Code\r\nLeft Join \"@HBT_MUNICIPIO\" A3 On A1.U_HBT_" +
            "MunMed = A3.Code\r\nWhere A0.DocEntry = {0}\r\n\r\nUnion All\r\n\r\nSelect \'GTA\' + \',\' + I" +
            "sNull(A2.U_Codigo,\'\') + \',\' + IsNull(A2.U_Desc,\'\') As \'Cadena\'\r\nFrom OINV A0\r\nIn" +
            "ner Join [@FEDIAN_SN] A1 On A0.CardCode = A1.Code\r\nInner Join [@FEDIAN_SN_TRIB] " +
            "A2 On A1.Code = A2.Code\r\nWhere A0.DocEntry = {0}\r\n\r\nUnion All\r\n\r\nSelect \'TOT\' + " +
            "\',\' + \r\nCast(Cast(Sum(A1.Linetotal) as decimal (15,6)) as Nvarchar(100)) + \',\' +" +
            " Case When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End + \',\' + \r\nCast(Cast(A0." +
            "BaseAmnt as decimal (15,6)) as Nvarchar(100)) + \',\' + Case When A0.DocCur = \'$\' " +
            "Then \'COP\' Else A0.DocCur End + \',\' + \r\nCast(Cast(A0.DocTotal as decimal (15,6))" +
            " as Nvarchar(100)) + \',\' + Case When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur E" +
            "nd + \',\' + \r\nCast(Cast(Sum(A1.Linetotal)-A0.DiscSum+A0.VatSum as decimal (14,0))" +
            " as Nvarchar(100)) + \',\' + Case When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur E" +
            "nd + \',\' + \r\nCast(Cast(A0.DiscSum as decimal (15,6)) as Nvarchar(100)) + \',\' + C" +
            "ase When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End + \',\' + \r\nCast(Cast(A0.Va" +
            "tSum as decimal (15,6)) as Nvarchar(100)) + \',\' + Case When A0.DocCur = \'$\' Then" +
            " \'COP\' Else A0.DocCur End + \',\' + \r\nCast(Cast(A0.DpmAmnt as decimal (15,6)) as N" +
            "varchar(100)) + \',\' + Case When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End + " +
            "\',\' + \'\' + \',\' + \'\' As \'Cadena\'\r\nFrom OINV A0\r\nInner Join INV1 A1 On A0.DocEntry" +
            " = A1.DocEntry\r\nWhere A0.DocEntry = {0}\r\nGroup By A0.DocCur, A0.BaseAmnt, A0.Doc" +
            "Total, A0.DiscSum, A0.VatSum, A0.DpmAmnt\r\n\r\nUnion All\r\n\r\nSelect \'TIM\' + \',\' + \'f" +
            "alse\' + \',\' + \r\nCast(Cast(A0.VatSum as decimal (15,6)) as Nvarchar(100))  + \',\' " +
            "+ Case When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End As \'Cadena\'\r\nFrom OINV" +
            " A0\r\nWhere A0.DocEntry = {0} And IsNull(A0.VatSum ,0) != 0\r\n\r\nUnion All\r\n\r\nSelec" +
            "t \'IMP\' + \',\' + IsNull(A2.U_SEI_FETributo,\'\') + \',\' + \r\nCast(Cast(Sum(A1.BaseSum" +
            ") as decimal (15,6)) as Nvarchar(100)) + \',\' + \r\nCase When A0.DocCur = \'$\' Then " +
            "\'COP\' Else A0.DocCur End + \',\' +\r\nCast(Cast(Sum(A1.TaxSum) as decimal (15,6)) as" +
            " Nvarchar(100)) + \',\' +\r\nCase When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End" +
            " + \',\' + \r\nCast(Cast(A1.TaxRate as decimal (14,2)) as Nvarchar(100)) \r\n+ \',\' + \'" +
            "\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' As \'Cadena\'\r\nFrom OINV A0\r\nInner Join INV4 A1" +
            " On A0.DocEntry = A1.DocEntry\r\nInner Join OSTC A2 On A1.StcCode = A2.Code\r\nWhere" +
            " A0.DocEntry = {0} And IsNull(A1.TaxSum ,0) != 0\r\nGroup By A0.DocCur, A1.TaxRate" +
            ", A2.U_SEI_FETributo\r\n\r\nUnion All\r\n\r\nSelect \'DSC\' + \',\' + \'false\' + \',\' + \r\nCast" +
            "(Cast(A0.DiscPrcnt as decimal (15,2)) as Nvarchar(100)) + \',\' + Cast(Cast(A0.Dis" +
            "cSum as decimal (15,6)) as Nvarchar(100)) + \',\' + \r\nCase When A0.DocCur = \'$\' Th" +
            "en \'COP\' Else A0.DocCur End + \',\' + IsNull(A0.U_SEI_FEDescu,\'\') + \',\' + IsNull(A" +
            "2.Descr,\'\') + \',\' +\r\nCast(Cast(Sum(A3.LineTotal) as decimal (15,6)) as Nvarchar(" +
            "100)) + \',\' + Case When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End + \r\n\',\' + " +
            "\'\' + \',\' + \'1\'  As \'Cadena\'\r\nFrom OINV A0\r\nLeft Join CUFD A1 On A1.TableID = \'OI" +
            "NV\' And A1.AliasID = \'SEI_FEDescu\'\r\nLeft Join UFD1 A2 On A2.TableID = A1.TableID" +
            " And A2.FieldID = A1.FieldID And A0.U_SEI_FEDescu = A2.FldValue\r\nLeft Join INV1 " +
            "A3 On A0.DocEntry = A3.DocEntry\r\nWhere A0.DocEntry = {0} And IsNull(A0.DiscSum,0" +
            ") != 0\r\nGroup By A0.DiscPrcnt, A0.DiscSum, A0.DocCur, A0.U_SEI_FEDescu, A2.Descr" +
            "\r\n\r\nUnion All\r\n\r\nSelect \'DRF\' + \',\' + IsNull(A2.U_NumResol,\'\') + \',\' + IsNull(CO" +
            "NVERT(char(10), A2.U_FechaDesde,126),\'\') + \',\' + IsNull(CONVERT(char(10), A2.U_F" +
            "echaHasta,126),\'\') + \',\' + \r\nIsNull(A1.BeginStr,\'\') + \',\' + IsNull(Cast(Cast(A1." +
            "InitialNum as int) as Nvarchar(100)),\'\') + \',\' + IsNull(Cast(Cast(A1.LastNum as " +
            "int) as Nvarchar(100)),\'\')\r\nFrom OINV A0\r\nInner Join NNM1 A1 On A0.Series = A1.S" +
            "eries\r\nInner Join \"@FEDIAN_NUMAUTORI\" A2 On A1.Series = A2.Code\r\nWhere A0.DocEnt" +
            "ry = {0} And IsNull(A1.LastNum,\'\') != \'\'\r\n\r\nUnion All\r\n\r\nSelect \r\n\'NOT,2_ La mer" +
            "cancía viaja por cuenta y riesgo del comprador. El vendedor se reserva el derech" +
            "o de dominio sobre la mercancía hasta su pago total. Con esta firma el comprador" +
            " declara haber recibido a satisfacción real y materialmente las mercancías descr" +
            "itas en este documento\' As \'Cadena\'\r\nFrom OADM A0\r\n\r\nUnion All\r\n\r\nSelect \r\n\'NOT," +
            "5_ ACTIVIDAD COMERCIAL 4659 - TARIFA 11.04 x 1000\' + \'|\' + \r\n\'IVA REGIMEN COMUN " +
            "- AUTORRETENEDOR RENTA RESOLUCION No. 008543 DE 08/13/09\' As \'Cadena\'\r\nFrom OADM" +
            " A0\r\n\r\nUnion All\r\n\r\nSelect \'NOT,6_ \' + A1.SlpName  As \'Cadena\'\r\nFrom OINV A0\r\nIn" +
            "ner Join OSLP A1 On A0.SlpCode = A1.SlpCode\r\nWhere A0.DocEntry = {0} And A0.SlpC" +
            "ode != -1\r\n\r\nUnion All\r\n\r\nSelect \r\n\'NOT,7_ IVA RÉGIMEN COMÚN\' + \'|\' + IsNull(A1." +
            "IntrntAdrs,\'\') As \'Cadena\'\r\nFrom OADM A0\r\nInner Join ADM1 A1 ON A0.Code= A1.Code" +
            "\r\n\r\nUnion All\r\n\r\nSelect \'NOT,12_ \' + REPLACE(REPLACE(REPLACE(Cast(IsNull(A0.Comm" +
            "ents,\'\') as Nvarchar(max)),CHAR(10),\' \'),CHAR(13),\' \'), \',\', \';\') As \'Cadena\'\r\nF" +
            "rom OINV A0\r\nInner Join OADM A1 On 1 =1 \r\nWhere A0.DocEntry = {0} And IsNull(A0." +
            "Comments,\'\') != \'\'\r\n\r\nUnion All\r\n\r\nSelect \'NOT,14_ \' + A0.LicTradNum + \'|\' + A1." +
            "TaxIdNum As \'Cadena\'\r\nFrom OINV A0\r\nInner Join OADM A1 On 1 =1 \r\nWhere A0.DocEnt" +
            "ry = {0}\r\n\r\nUnion All\r\n\r\nSelect \'OVT\' + \',\' + \'01C\' + \',\' + Cast(Cast(Sum(A1.WTA" +
            "mnt) as decimal (14,0)) as Nvarchar(100)) + \',\' + \r\nCase When A0.DocCur = \'$\' Th" +
            "en \'COP\' Else A0.DocCur End + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' As \'Cadena\'\r\nFrom O" +
            "INV A0\r\nInner Join INV5 A1 ON A0.DocEntry = A1.AbsEntry \r\nInner Join OWHT A2 On " +
            "A1.WTCode = A2.WTCode\r\nWhere A2.U_HBT_TipoAutoRet = \'4\' And A2.U_HBT_TipRet != \'" +
            "0\' And IsNull(A1.WTAmnt,0) != 0 And A0.DocEntry = {0}\r\nGroup By A0.DocEntry, A0." +
            "DocCur\r\n\r\nUnion All\r\n\r\nSelect \'MEP\' + \',\' + IsNull(A0.U_SEI_FEMedPago,\'\') + \',\' " +
            "+ Case When A1.\"ExtraMonth\" + A1.\"ExtraDays\" <= 0 Then \'1\' Else \'2\' End  + \',\' +" +
            "\r\nConvert(char(10), A0.DocDueDate,126) + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + " +
            "\'\' + \',\' + \'\' + \',\' + \'\' As \'Cadena\'\r\nFrom OINV A0\r\nInner Join OCTG A1 On A0.Gro" +
            "upNum = A1.GroupNum\r\nWhere A0.DocEntry = {0} And IsNull(A0.U_SEI_FEMedPago,\'\') !" +
            "= \'\'\r\n\r\nUnion All\r\n\r\nSelect \'CTS\' + \',\' + \'BIOT01\' + \',\' + \'\' + \',\' + \'\' + \',\' +" +
            " \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\'\r\nFrom OADM\r\n\r\nUnion All\r\n\r\nSelec" +
            "t \'CDN\' + \',\' + A0.U_SEI_FEConcepND + \',\' + A2.Descr + \',\' + \'\'\r\nFrom OINV A0\r\nI" +
            "nner Join CUFD A1 On A1.TableID = \'OINV\' And A1.AliasID = \'SEI_FEConcepND\'\r\nInne" +
            "r Join UFD1 A2 On A2.TableID = A1.TableID And A2.FieldID = A1.FieldID And A0.U_S" +
            "EI_FEConcepND = A2.FldValue\r\nWhere A0.DocEntry = {0}\r\n\r\nUnion All\r\n\r\nSelect \'DCN" +
            "\' + \',\' + A2.Descr\r\nFrom OINV A0\r\nInner Join CUFD A1 On A1.TableID = \'OINV\' And " +
            "A1.AliasID = \'SEI_FEConcepND\'\r\nInner Join UFD1 A2 On A2.TableID = A1.TableID And" +
            " A2.FieldID = A1.FieldID And A0.U_SEI_FEConcepND = A2.FldValue\r\nWhere A0.DocEntr" +
            "y = {0}\r\n\r\n)T0\r\n\r\nUnion All\r\n\r\nSelect A1.LineNum, 2 as \'ordenplano\', \'ITE\' + \',\'" +
            " + Cast(A1.VisOrder+1 as Nvarchar(100)) + \',\' + \'\' + \',\' +\r\nCase When A1.Quantit" +
            "y = 0 Then Cast(Cast(1 as decimal (14,0)) as Nvarchar(100)) \r\nElse Cast(Cast(A1." +
            "Quantity as decimal (14,4)) as Nvarchar(100)) End + \',\' + \r\nCASE \r\nWHEN IsNull(A" +
            "1.\"UomCode\",\'\') = \'Manual\' Then IsNull((Select IsNull(P0.\"U_DIAN_UM\",\'\') From \"@" +
            "FEDIAN_HOMOL_UM\" P0 Where P0.\"U_SAP_UM\" = A1.\"unitMsr\"),\'\') \r\nElse IsNull((Selec" +
            "t IsNull(P0.\"U_DIAN_UM\",\'\') From \"@FEDIAN_HOMOL_UM\" P0 Where P0.\"U_SAP_UM\" = A1." +
            "\"UomCode\"),\'\') End + \',\' + \r\nCast(Cast(A1.LineTotal as decimal (15,6)) as Nvarch" +
            "ar(100)) + \',\' + Case When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End + \',\' +" +
            "\r\nCase When A1.Quantity = 0 Then Cast(Cast(A1.LineTotal/1 as decimal (15,6)) as " +
            "Nvarchar(100)) \r\nElse Cast(Cast(A1.LineTotal/A1.Quantity as decimal (15,6)) as N" +
            "varchar(100)) End + \',\' + Case When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur En" +
            "d + \',\' + \r\n\'\' + \',\' + \'\' + \',\' + Replace(A1.Dscription,\',\',\'.\') + \',\' + \'\' + \'," +
            "\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \r\n\'\' + \',\' + Case When A0.Doctyp" +
            "e = \'S\' Then A1.AcctCode Else Replace(A1.ItemCode,\',\',\'.\') End + \',\' + \r\nCast(Ca" +
            "st(A1.LineTotal as decimal (15,6)) as Nvarchar(100)) + \',\' + Case When A0.DocCur" +
            " = \'$\' Then \'COP\' Else A0.DocCur End + \',\' + \r\nCast(Cast(A1.LineTotal as decimal" +
            " (15,6)) as Nvarchar(100)) + \',\' + Case When A0.DocCur = \'$\' Then \'COP\' Else A0." +
            "DocCur End + \',\' + \r\nCast(Cast(A1.LineTotal as decimal (15,6)) as Nvarchar(100))" +
            " + \',\' + Case When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End + \',\' + \r\n\'\' + " +
            "\',\' + \'\' + \',\' + \r\nCase When A1.Quantity = 0 Then Cast(Cast(1 as decimal (14,0))" +
            " as Nvarchar(100)) \r\nElse Cast(Cast(A1.Quantity as decimal (14,4)) as Nvarchar(1" +
            "00)) End + \',\' + CASE \r\nWHEN IsNull(A1.\"UomCode\",\'\') = \'Manual\' Then IsNull((Sel" +
            "ect IsNull(P0.\"U_DIAN_UM\",\'\') From \"@FEDIAN_HOMOL_UM\" P0 Where P0.\"U_SAP_UM\" = A" +
            "1.\"unitMsr\"),\'\') \r\nElse IsNull((Select IsNull(P0.\"U_DIAN_UM\",\'\') From \"@FEDIAN_H" +
            "OMOL_UM\" P0 Where P0.\"U_SAP_UM\" = A1.\"UomCode\"),\'\') End + \',\' + \r\nCast(Cast(A1.L" +
            "ineTotal as decimal (15,6)) as Nvarchar(100)) + \',\' + Case When A0.DocCur = \'$\' " +
            "Then \'COP\' Else A0.DocCur End + \',\' +\r\nCast(A0.SlpCode as Nvarchar(100)) as \'Cad" +
            "ena\'\r\nFrom OINV A0 \r\nInner Join INV1 A1 On A0.DocEntry = A1.DocEntry\r\nWhere A0.D" +
            "ocEntry = {0}\r\n\r\nUnion All\r\n\r\nSelect A1.LineNum, 3 as \'ordenplano\', \'IAE\' + \',\' " +
            "+ Cast(IsNull(A1.ItemCode,\'\') as Nvarchar(100)) + \',\' + \r\nIsNull(A2.U_SEI_FEIden" +
            "t,\'\') + \',\' + \'\' + \',\' + \'\' as \'cadena\'\r\nFrom OINV A0 \r\nInner Join INV1 A1 On A0" +
            ".DocEntry = A1.DocEntry\r\nInner Join OITM A2 On A1.ItemCode = A2.ItemCode\r\nWhere " +
            "A0.DocEntry = {0}\r\n\r\nUnion All\r\n\r\nSelect A1.LineNum, 3 as \'ordenplano\', \'TII\' + " +
            "\',\' + Cast(Cast(A2.TaxSum as decimal (14,0)) as Nvarchar(100)) + \',\' + \r\nCase Wh" +
            "en A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End + \',\' + \'false\'\r\nFrom OINV A0 \r" +
            "\nInner Join INV1 A1 On A0.DocEntry = A1.DocEntry\r\nInner Join INV4 A2 On A1.DocEn" +
            "try = A2.DocEntry And A1.LineNum = A2.LineNum\r\nWhere A0.DocEntry = {0} And A2.Ex" +
            "pnsCode = -1\r\nGroup By A0.DocEntry, A0.DocCur, A2.TaxSum, A1.LineNum\r\n\r\nUnion Al" +
            "l\r\n\r\nSelect A1.LineNum, 4 as \'ordenplano\', \'IIM\' + \',\' + IsNull(A3.U_SEI_FETribu" +
            "to,\'\') + \',\' + Cast(Cast(A2.TaxSum as decimal (14,0)) as Nvarchar(100)) + \',\' + " +
            "\r\nCase When A0.DocCur = \'$\' Then \'COP\' Else A0.DocCur End + \',\' + Cast(Cast(A2.B" +
            "aseSum as decimal (14,0)) as Nvarchar(100)) + \r\n\',\' + Case When A0.DocCur = \'$\' " +
            "Then \'COP\' Else A0.DocCur End + \',\' + Cast(Cast(A2.TaxRate as decimal (14,2)) as" +
            " Nvarchar(100))\r\n+ \',\' + \'\' + \',\' + \'\' + \',\' + \'\' + \',\' + \'\' as \'Cadena\'\r\nFrom O" +
            "INV A0 \r\nInner Join INV1 A1 On A0.DocEntry = A1.DocEntry\r\nInner Join INV4 A2 On " +
            "A1.DocEntry = A2.DocEntry And A1.LineNum = A2.LineNum\r\nInner Join OSTC A3 On A2." +
            "StcCode = A3.Code\r\nWhere A0.DocEntry = {0} And A2.ExpnsCode = -1\r\nGroup By A0.Do" +
            "cEntry, A0.DocCur, A2.BaseSum, A2.TaxRate, A2.TaxSum, A1.LineNum, A3.U_SEI_FETri" +
            "buto\r\n)C0 Order by LineNum, ordenplano;")]
        public string NotaDebito {
            get {
                return ((string)(this["NotaDebito"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n\t\t\t\t\tSelect * From [@FEDIAN_INTERF_ERR] Where IsNull(Cast(U_MsgExter as Nvarcha" +
            "r(2500)), \'\') = \'{0}\'\r\n\t\t\t\t")]
        public string Msginter {
            get {
                return ((string)(this["Msginter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n\t\t\t\t\tSelect * from [@FEDIAN_CODDOC] Order By Code\r\n\t\t\t\t")]
        public string cmbTipodoc {
            get {
                return ((string)(this["cmbTipodoc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
					Select U_Status, 
					Case 
					When U_Status = '1' Then 'Procesado' 
					When U_Status = '2' Then 'En Proceso' 
					When U_Status = '3' Then 'Error' 
					When U_Status = '10' Then 'Procesado'
					When U_Status = '102' Then 'Error'
					When U_Status = '106' Then 'Error' else 'En Proceso' End
					from [@FEDIAN_MONITORLOG]
					Where IsNull(U_Status,'') != ''
					Group By U_Status
					Order By U_Status
				")]
        public string cmbEstado {
            get {
                return ((string)(this["cmbEstado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Select A0.""Code"", A0.""U_DocNum"", A0.""U_Folio"", A0.""U_Prefijo"", A0.""U_DocType"", A0.""U_ObjType"", IsNull(Cast(A0.""U_Fecha_Envio"" as nvarchar(100)),'') as ""U_Fecha_Envio""
From ""@FEDIAN_MONITORLOG"" A0
Where IsNull(A0.""U_Status"",'') = '' or IsNull(A0.""U_Status"",'') In ({0})")]
        public string ReSendAuto {
            get {
                return ((string)(this["ReSendAuto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n\t\t\t\t\tSelect IsNull(Max(cast(Code as Int)),0)+1 As \'NextCode\' From [@FEDIAN_MONI" +
            "TORLOG]\r\n\t\t\t\t")]
        public string MaxLog {
            get {
                return ((string)(this["MaxLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Select A2.""U_SEI_FETributo"" as ""CodigoImpuesto"", A2.""Name"" as ""NombreImpuesto"",
'False' as ""EsRetencionImpuesto"", Sum(A1.""BaseSum"") as ""BaseImponible"", Cast(A1.""TaxRate"" as decimal(19,2)) as ""Porcentaje"",
Sum(A1.""TaxSum"") as ""ValorImpuesto""
From OINV A0
Inner Join INV4 A1 On A0.""DocEntry"" = A1.""DocEntry"" And A1.""RelateType"" = '1'
Inner Join OSTC A2 On A1.""StcCode"" = A2.""Code""
Where A0.""DocEntry"" = {0}
Group By A2.""U_SEI_FETributo"", A2.""Name"", A1.""TaxRate""

Union All

Select A2.""U_SEI_FETributo"" as ""CodigoImpuesto"", A2.""WTName"" as ""NombreImpuesto"",
'False' as ""EsRetencionImpuesto"", Sum(A1.""U_HBT_BaseRet"") as ""BaseImponible"", Cast(A1.""Rate"" as decimal(19,2)) as ""Porcentaje"",
Sum(A1.""WTAmnt"") as ""ValorImpuesto""
From OINV A0
Inner Join INV5 A1 On A0.""DocEntry"" = A1.""AbsEntry""
Inner Join OWHT A2 On A1.""WTCode"" = A2.""WTCode""
Where A0.""DocEntry"" = {0}
Group By A2.""U_SEI_FETributo"", A2.""WTName"", A1.""Rate""")]
        public string impFac {
            get {
                return ((string)(this["impFac"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string impNC {
            get {
                return ((string)(this["impNC"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string impND {
            get {
                return ((string)(this["impND"]));
            }
            set {
                this["impND"] = value;
            }
        }
    }
}
